### PR TITLE
Suggestions to error list

### PR DESCRIPTION
**Pull request by mmarsman1**
These are a couple of suggestions to make the list of errors more alike across the different analyses.

Please feel free to discuss @jonathon-love @AlexanderLyNL @EJWagenmakers @raviselker

### CODE REVIEW

**Comment by EJWagenmakers** [comment]
All looks good except for one issue concerning "less" vs "fewer"
E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by jonathon-love** [comment]
hey @ravi,
@mmarsman1 has proposed some burdening changes to the ANOVA.

in other news, i've implemented these for the t-tests

**Comment by mmarsman1** [comment]
I implemented these for the Bayesian Linear models.

@AlexanderLyNL I think this makes the reported errors more in line with very similar error messages in other analyses. For instance, "not enough observations" whereas other messages speak of "too few observations". We could also change the other messages to yours of course :)

@EJWagenmakers will change "less than" into "fewer than"

@jonathon-love we do need to keep this list in line with the actual errors :) Shall I check that once the dust settles on these burdening changes, but prior to the 0.6?

**Comment by AlexanderLyNL** [comment]
Sample correlation coefficient r is undefined - one or more of the variables contain all the same value (zero variance)

of the???? contain all the same value???

**Comment by mmarsman1** [comment]
What are you trying to say?

**Comment by mmarsman1** [comment]
Would we want to change "Sample correlation coefficient r" to "Pearson correlation coefficient" as we may introduce other correlations in the future? 
Also as small *r* is used in the error messages, yet a capital *R* appears in the Table.

**Comment by mmarsman1** [comment]
@jonathon-love could you merge these so that I can rebase?

**Pull request merged**
