### PR TITLE
Use ReadStat 1.1.9 and add -Wno-strict-prototypes

### PR DESCRIPTION
**Pull request by JorisGoosen**
should fix last problem in https://github.com/jasp-stats/INTERNAL-jasp/issues/2299

### CODE REVIEW

**Comment by JorisGoosen** [comment]
Hey @koenderks can you try building with this branch?

If it works we can merge this.

**Comment by JorisGoosen** [comment]
Dont forget `git update submodules`!
And it would be best to start from a fresh build folder.

**Comment by koenderks** [comment]
Will give it a try!

**Comment by koenderks** [comment]
Here is the build log for the failed build:

```
12:37:45: Running steps for project JASP...
12:37:45: Starting: "/Users/koenderks/Qt/Tools/CMake/CMake.app/Contents/bin/cmake" --build /Users/koenderks/GitHub/JASP/build-jasp-desktop-Qt_6_5_0_for_macOS-Debug --target all
[1/306 12.6/sec] Automatic MOC and UIC for target QMLComponents_resources_1
[2/306 24.3/sec] Automatic MOC and UIC for target R-Interface
[3/306 34.9/sec] Automatic MOC and UIC for target Common
[4/306 29.9/sec] Building CXX object R-Interface/CMakeFiles/R-Interface.dir/R-Interface_autogen/mocs_compilation.cpp.o
[5/306 37.0/sec] Building CXX object Common/CMakeFiles/Common.dir/Common_autogen/mocs_compilation.cpp.o
[6/306 38.3/sec] Running rcc for resource qmlComponents
[7/306 22.2/sec] Building CXX object QMLComponents/CMakeFiles/QMLComponents_resources_1.dir/.rcc/qrc_qmlComponents.cpp.o
[8/306 19.1/sec] Building CXX object QMLComponents/CMakeFiles/QMLComponents_resources_1.dir/QMLComponents_resources_1_autogen/mocs_compilation.cpp.o
[9/306 8.6/sec] Building CXX object Common/CMakeFiles/Common.dir/appinfo.cpp.o
[10/306 8.1/sec] Building CXX object R-Interface/CMakeFiles/R-Interface.dir/__/Common/json/json_writer.cpp.o
[11/306 8.2/sec] Building CXX object R-Interface/CMakeFiles/R-Interface.dir/__/Common/json/json_value.cpp.o
[12/306 8.8/sec] Building CXX object Common/CMakeFiles/Common.dir/dirs.cpp.o
[13/306 9.1/sec] Building CXX object R-Interface/CMakeFiles/R-Interface.dir/__/Common/json/json_reader.cpp.o
[14/306 9.6/sec] Building CXX object Common/CMakeFiles/Common.dir/columntype.cpp.o
[15/306 10.2/sec] Building CXX object Common/CMakeFiles/Common.dir/enginedefinitions.cpp.o
[16/306 10.7/sec] Building CXX object Common/CMakeFiles/Common.dir/processinfo.cpp.o
[17/306 11.0/sec] Building CXX object Common/CMakeFiles/Common.dir/timers.cpp.o
[18/306 11.5/sec] Running qmlimportscanner for JASP
[19/306 10.0/sec] Building CXX object Common/CMakeFiles/Common.dir/columnencoder.cpp.o
[20/306 7.4/sec] Building CXX object Common/CMakeFiles/Common.dir/json/json_writer.cpp.o
[21/306 7.5/sec] Building CXX object Common/CMakeFiles/Common.dir/json/json_value.cpp.o
[22/306 7.6/sec] Building CXX object Common/CMakeFiles/Common.dir/json/json_reader.cpp.o
[23/306 7.8/sec] Building CXX object Common/CMakeFiles/Common.dir/utils.cpp.o
[24/306 8.1/sec] Building CXX object Common/CMakeFiles/Common.dir/utilenums.cpp.o
[25/306 8.4/sec] Building CXX object Common/CMakeFiles/Common.dir/tempfiles.cpp.o
[26/306 8.5/sec] Building CXX object Common/CMakeFiles/Common.dir/r_functionwhitelist.cpp.o
[27/306 8.8/sec] Building CXX object Common/CMakeFiles/Common.dir/log.cpp.o
/Users/koenderks/GitHub/JASP/jasp-desktop/Common/log.cpp:181:35: warning: 'codecvt_utf8_utf16<wchar_t, 1114111, 0>' is deprecated [-Wdeprecated-declarations]
        static std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>> strCvt;
                                         ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/c++/v1/codecvt:588:28: note: 'codecvt_utf8_utf16<wchar_t, 1114111, 0>' has been explicitly marked deprecated here
class _LIBCPP_TEMPLATE_VIS _LIBCPP_DEPRECATED_IN_CXX17 codecvt_utf8_utf16
                           ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/c++/v1/__config:837:41: note: expanded from macro '_LIBCPP_DEPRECATED_IN_CXX17'
#    define _LIBCPP_DEPRECATED_IN_CXX17 _LIBCPP_DEPRECATED
                                        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/c++/v1/__config:810:49: note: expanded from macro '_LIBCPP_DEPRECATED'
#      define _LIBCPP_DEPRECATED __attribute__((deprecated))
                                                ^
/Users/koenderks/GitHub/JASP/jasp-desktop/Common/log.cpp:181:14: warning: 'wstring_convert<std::codecvt_utf8_utf16<wchar_t, 1114111, 0>>' is deprecated [-Wdeprecated-declarations]
        static std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>> strCvt;
                    ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/c++/v1/locale:3621:28: note: 'wstring_convert<std::codecvt_utf8_utf16<wchar_t, 1114111, 0>>' has been explicitly marked deprecated here
class _LIBCPP_TEMPLATE_VIS _LIBCPP_DEPRECATED_IN_CXX17 wstring_convert
                           ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/c++/v1/__config:837:41: note: expanded from macro '_LIBCPP_DEPRECATED_IN_CXX17'
#    define _LIBCPP_DEPRECATED_IN_CXX17 _LIBCPP_DEPRECATED
                                        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/c++/v1/__config:810:49: note: expanded from macro '_LIBCPP_DEPRECATED'
#      define _LIBCPP_DEPRECATED __attribute__((deprecated))
                                                ^
2 warnings generated.
[28/306 7.8/sec] Building CXX object R-Interface/CMakeFiles/R-Interface.dir/jasprcpp.cpp.o
FAILED: R-Interface/CMakeFiles/R-Interface.dir/jasprcpp.cpp.o 
/usr/bin/clang++ -DBUILDING_JASP -DJASP_DEBUG -DJASP_R_INTERFACE_LIBRARY -DJASP_USES_QT_HERE -DPRINT_ENGINE_MESSAGES -DQT_CORE_LIB -DQT_NO_DEPRECATED_WARNINGS -I/Users/koenderks/GitHub/JASP/build-jasp-desktop-Qt_6_5_0_for_macOS-Debug/R-Interface -I/Users/koenderks/GitHub/JASP/jasp-desktop/R-Interface -I/Users/koenderks/GitHub/JASP/build-jasp-desktop-Qt_6_5_0_for_macOS-Debug/R-Interface/R-Interface_autogen/include -I/Users/koenderks/GitHub/JASP/jasp-desktop/Common -I/Users/koenderks/GitHub/JASP/jasp-desktop/CommonData -I/Users/koenderks/GitHub/JASP/jasp-desktop/Common/json -I/Users/koenderks/GitHub/JASP/build-jasp-desktop-Qt_6_5_0_for_macOS-Debug/Frameworks/R.framework/Versions/4.2-arm64/Resources/include -I/Users/koenderks/GitHub/JASP/build-jasp-desktop-Qt_6_5_0_for_macOS-Debug/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/Rcpp/include -I/Users/koenderks/GitHub/JASP/build-jasp-desktop-Qt_6_5_0_for_macOS-Debug/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/RInside/include -isystem /Users/koenderks/.conan/data/boost/1.78.0/_/_/package/5ecffe865949145d1b4eea098477ec549ebbfe24/include -isystem /Users/koenderks/Qt/6.5.0/macos/lib/QtCore.framework/Headers -iframework /Users/koenderks/Qt/6.5.0/macos/lib -isystem /Users/koenderks/Qt/6.5.0/macos/mkspecs/macx-clang -isystem /Users/koenderks/Qt/6.5.0/macos/include -g -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk -mmacosx-version-min=11.0 -F/Users/koenderks/GitHub/JASP/build-jasp-desktop-Qt_6_5_0_for_macOS-Debug/Frameworks  -std=gnu++20 -MD -MT R-Interface/CMakeFiles/R-Interface.dir/jasprcpp.cpp.o -MF R-Interface/CMakeFiles/R-Interface.dir/jasprcpp.cpp.o.d -o R-Interface/CMakeFiles/R-Interface.dir/jasprcpp.cpp.o -c /Users/koenderks/GitHub/JASP/jasp-desktop/R-Interface/jasprcpp.cpp
In file included from /Users/koenderks/GitHub/JASP/jasp-desktop/R-Interface/jasprcpp.cpp:18:
In file included from /Users/koenderks/GitHub/JASP/jasp-desktop/R-Interface/jasprcpp.h:21:
In file included from /Users/koenderks/GitHub/JASP/build-jasp-desktop-Qt_6_5_0_for_macOS-Debug/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/RInside/include/RInside.h:26:
In file included from /Users/koenderks/GitHub/JASP/build-jasp-desktop-Qt_6_5_0_for_macOS-Debug/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/RInside/include/RInsideCommon.h:38:
In file included from /Users/koenderks/GitHub/JASP/build-jasp-desktop-Qt_6_5_0_for_macOS-Debug/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/Rcpp/include/Rcpp.h:78:
In file included from /Users/koenderks/GitHub/JASP/build-jasp-desktop-Qt_6_5_0_for_macOS-Debug/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/Rcpp/include/Rcpp/sugar/sugar.h:31:
In file included from /Users/koenderks/GitHub/JASP/build-jasp-desktop-Qt_6_5_0_for_macOS-Debug/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/Rcpp/include/Rcpp/sugar/functions/functions.h:42:
/Users/koenderks/GitHub/JASP/build-jasp-desktop-Qt_6_5_0_for_macOS-Debug/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/Rcpp/include/Rcpp/sugar/functions/sapply.h:36:19: error: no template named 'result_of' in namespace 'std'; did you mean 'traits::result_of'?
        typedef typename ::std::result_of<Function(typename SugarExpression::stored_type)>::type type;
                         ^~~~~~~~~~~~~~~~
                         traits::result_of
/Users/koenderks/GitHub/JASP/build-jasp-desktop-Qt_6_5_0_for_macOS-Debug/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/Rcpp/include/Rcpp/traits/result_of.h:30:8: note: 'traits::result_of' declared here
struct result_of{
       ^
1 error generated.
[29/306 7.1/sec] Building CXX object Common/CMakeFiles/Common.dir/version.cpp.o
```

**Comment by koenderks** [comment]
Actually, this is the FULL build log: 
[log.txt](https://github.com/jasp-stats/jasp-desktop/files/11169760/log.txt)

**Comment by JorisGoosen** [comment]
Aah right!

Forgot a line...

**Comment by JorisGoosen** [comment]
Can you try it again now?

**Comment by koenderks** [comment]
Hij is gebouwd!

**Comment by JorisGoosen** [comment]
Nou approve de PR maar dan, mr reviewer ;)

**Pull request merged**
