### PR TITLE
gmp was updated on conan and should now work on macos arm

### PR DESCRIPTION
**Pull request by JorisGoosen**
no more workaround!

### CODE REVIEW

**Comment by RensDofferhoff** [comment]
Seems to break the build system from clean build. Error while installing MatrixModels

**Review by boutinb — APPROVED** [review]

**Comment by JorisGoosen** [comment]
This works great after https://github.com/jasp-stats/jasp-desktop/pull/5219 is merged

**Comment by RensDofferhoff** [comment]
But this will merge unto stable and we cant merge development because of the R4.3.1 version update

**Comment by shun2wang** [comment]
Can we switch development branch as the default branch? the stable branch should keep for a release and dev branch is higher frequency so we can do  less rebase:-)

**Comment by JorisGoosen** [comment]
> But this will merge unto stable and we cant merge development because of the R4.3.1 version update

Now its on development ^^

I dont have a mac arm right now (only tomorrow again)

**Comment by JorisGoosen** [comment]
> Can we switch development branch as the default branch? the stable branch should keep for a release and dev branch is higher frequency so we can do less rebase:-)

Maybe this is not a bad idea, lets talk about it in MatterMost

**Pull request merged**
