### PR TITLE
changed type to number

### LINKED ISSUE #2889: Decimal place oddity
Hi folks
I was just playing around with some descriptive data for students and noticed that the values of SE kurtosis default to 16 decimal places.  Changing this in preferences has no effect.

Cheers
Mark

JASP 0.9.1
Windows 10

dp error

### PR DESCRIPTION
**Pull request by vandenman**
Now rounds skewness to the right amount of decimals. This fixes #2889.

image

### CODE REVIEW

**Comment by AlexanderLyNL** [comment]
"number of decimals", but other than that good fix

**Comment by vandenman** [comment]
@JorisGoosen jaspResults error at line 3655 of travis with:

image

I'll have a look at the other error.

**Comment by JorisGoosen** [comment]
Commit 481696417a144198549acae112d98ef02c6a38bb should fix the travis problem

**Comment by vandenman** [comment]
I changed the unit tests for a couple of reasons:

- JASP 0.9.1.0 also showed the same output.
- The analyses corresponding to the unit-tests will be rewritten (hopefully soon).

Now Travis is happy again.

**Pull request merged**
