### PR TITLE
Version Update

### PR DESCRIPTION
**Pull request by dropmann**

### CODE REVIEW

**Comment by jonathon-love** [comment]
hey, this has merge conflicts. can you do a rebase, and then open a pull request?

**Comment by dropmann** [comment]
How do i rebase when i'm now three ahead?

**Comment by jonathon-love** [comment]
git reset HEAD~3

this should undo your last three commits, and return your changes to the working directory.
stash your changes.
rebase
unstash
fix the conflicts
commit
pull request

**Comment by dropmann** [comment]
ah yes, thanks

**Comment by jonathon-love** [comment]
oh wait!
after you commit, you'll have to do a

      git push --force

to nuke the 3 commits in github.

**Comment by dropmann** [comment]
where are you at the moment

**Comment by jonathon-love** [comment]
one of these upstairs rooms

**Pull request closed without merging**
