### PR TITLE
Adding Mixed Models

### PR DESCRIPTION
**Pull request by JorisGoosen**
from https://github.com/jasp-stats/MixedModels/commit/9ea02fb31e97ebb21d32ea71954106e1186b93f8

I think this would be all?

### CODE REVIEW

**Comment by JorisGoosen** [comment]
Ah yeah, so the unittests fail, but @FBartos is working on that right?

**Comment by FBartos** [comment]
yes, the unit tests are not done yet

**Review by FBartos — APPROVED** [review]
Looks good to me.
I think that @EJWagenmakers wanted to have them on the main ribbon.

**Comment by JorisGoosen** [comment]
As in, by default?

**Comment by FBartos** [comment]
> As in, by default?

yes

**Review by TimKDJ — APPROVED** [review]
@FBartos will you open a separate PR with the fixed tests?

**Comment by FBartos** [comment]
Yes, I can do that.

**Review by FBartos — APPROVED** [review]

**Pull request merged**
