### PR TITLE
Modules/network

### PR DESCRIPTION
**Pull request by vandenman**
Jasp module for network analysis.

Some notes:

- Present in both debug and release.
- Tim's progressbar is not implemented yet.
- Thorough testing still needs to be done.
- The helpfile is far from complete (some references are lacking).

Feedback, comments, suggestions for improvement are welcome!

### CODE REVIEW

**Comment by akashrajkn** [comment]
@vandenman can you please squash the commits. (a lot of merge-commits are duplicated).

**Comment by TimKDJ** [comment]
Added the progress bar functionality. You can find documentation [here](https://github.com/jasp-stats/jasp-desktop/blob/development/Docs/development/r-analyses-guide.md).

**Comment by TimKDJ** [comment]
@vandenman Bruno just merged the progress bar stuff so you're good to go.

**Comment by akashrajkn** [comment]
@vandenman please use `rebase` instead of `merge`. Rebase will not create merge commits, and it'll be easier to see the changes commit-wise. Cheers.

**Comment by akashrajkn** [comment]
Pull request #2010 has all the recent changes.

**Pull request closed without merging**
