### PR TITLE
Custom Contrast is not updated when the data is filtered

### PR DESCRIPTION
**Pull request by boutinb**
Fixes https://github.com/jasp-stats/INTERNAL-jasp/issues/1795
2 problems: the Custom Contrast model was not aware of filter changes, and the labels were read not taking into account of the filter.

### CODE REVIEW

**Comment by JorisGoosen** [comment]
Doesn't this change break the variableswindow?

**Comment by JorisGoosen** [comment]
I think it would be better to let your ListModel take the labels via https://github.com/jasp-stats/jasp-desktop/blob/stable/Desktop/data/datasettablemodel.h because then the filter is already applied anyway right?

**Comment by JorisGoosen** [comment]
Ooh sorry... I suggested work for nothing.

Do you have a testfile? 
Because when I read the issue I don't know how to get to a reproducible path :p

But I think in your latest code it only works if you don't show the filtered rows in the dataview. So I made a small fix:
https://github.com/JorisGoosen/jasp-desktop/commit/64fe7cd570cf77802d8888161260bfd4437503de

(I also changed the `notUsed` to a set, because I figured if you wanted the speedup from `int max=rowCount();` you would also appreciate the hashing powers vs list-searching ;) )

But I can't test whether my code is necessary and/or works

**Comment by boutinb** [comment]
This code adds a new reference between a QML CustomContrast object and the DataSet, and as, for the R Syntax project, I'm busy to separate these kinds of reference in order to make a loose library containing QML objects that can be loaded in a R package, I prefer to base this PR to development, and to merge it only after the PR that implements the loose library is merged.

**Review by JorisGoosen — APPROVED** [review]
too bad I cant test it but it looks fine

**Pull request merged**
