### PR TITLE
moved color palette and changed default

### PR DESCRIPTION
**Pull request by vandenman**
Fixes https://github.com/jasp-stats/INTERNAL-jasp/issues/535

The new default for color palette is `colorblind`.

The position of colorpalette dropdown is now in the top left above `Distribution plots`.

### CODE REVIEW

**Review by AlexanderLyNL — APPROVED** [review]
Wonderful, this looks very nice. I like how you added all the new features. I also like how you'd retained the meaty colour on the violin plot, but shouldn't that also change if we change the colour palette?

**Comment by TimKDJ** [comment]
@vandenman see Lexi's comment. Should the violin change?

**Comment by vandenman** [comment]
I guess it should.

**Comment by TimKDJ** [comment]
Alright, then I'll wait with merging

**Comment by vandenman** [comment]
color palette now also works for the box plot. I've made some small changes to the box plot as well (it now uses `themeJaspRaw`) but if the unit tests pass then I think this should be good to merge.

image

**Review by TimKDJ — CHANGES_REQUESTED** [review]
The color schemes work nicely for all but `ggplot2` -- if you choose that one the piecharts don't play ball:

[colorsPiecharts.jasp.zip](https://github.com/jasp-stats/jasp-desktop/files/3808169/colorsPiecharts.jasp.zip)

**Review by TimKDJ — APPROVED** [review]

**Pull request merged**
