### PR TITLE
[WIP] Translation to German

### PR DESCRIPTION
**Pull request by JoKeyser**
Although this is still work in progress, it may make sense to merge this any time now, in case Weblate is becoming available (#4213).
The idea is to have this as a place for collaboration and to keep track of a German translation of JASP.
See also issue https://github.com/jasp-stats/jasp-issues/issues/661.

Teaser preview:

JASP-Preview13-1

### CODE REVIEW

**Comment by boutinb** [comment]
First of all, thank you really much for your effort! That's really useful, and we will be able to have a german version soon tanks to you. As I told you in the issue, these 2 po files covers most of the interface and the results of the analyses. We will make some changes soon, so that also some menus, and the help file will be added in this po file.
What would be great is that you can test yourself, and change immediately your translation, without to wait for us to make a release with your po files.
For this, first 2 questions: which OS do you use? And do you have Qt already installed?

**Comment by JoKeyser** [comment]
@boutinb, thanks, I'm glad that you agree with this approach. My hope with this WIP-PR is that maybe I don't have to do it all by myself, I guess we'll see how fast it will go.

It will really be helpful to be able to compile JASP and see the translations in context. I'm using Arch Linux, and compiling and running it works fine (with minor deviations from [jasp-building-guide.md](https://github.com/jasp-stats/jasp-desktop/blob/stable/Docs/development/jasp-building-guide.md#linux)). (I als tried Ubuntu 18.04 LTS but gave up after first installing R 3.6 [using newer apt sources](https://cran.rstudio.com/bin/linux/ubuntu/README.html), and Qt5.14 [from here](https://www.qt.io/download). Even though I eventually managed to compile it, some qt-stuff was still missing at runtime, and I lost my interest in pursuing, given that Arch works fine).

Regarding the git workflow: I see you force-pushed the new `stable` branch; should I keep merging from this one, or `development`? (Besides, all intermediate commits should be squashed before the merge.)

**Comment by JoKeyser** [comment]
@boutinb I managed to compile my branch, but I can't yet select my (unfinished) translation. I suspect the language entry must be registered somewhere first? (I mean the code must be made aware of another language option?)

**Comment by FransMeerhoff** [comment]
HI @JoKeyser 
Yes you are perfectly right. I just made a PR with a document that describes how to do that.  Could you check if that's enough information for you to  test your translated files?

**Comment by FransMeerhoff** [comment]
Hi @JoKeyser 
Some more info if you want to test your translation so far in your own environment.
It is described in https://github.com/jasp-stats/jasp-desktop/blob/stable/Docs/development/translate.md
Here is documented that you could use the lrelease tool to generate a binary .qm file.
Afterwards you could copy this file to your installation folder of JASP and then a german item should appear in the dropdown box. Thanks  a lot anyway.

**Comment by JoKeyser** [comment]
Hi @FransMeerhoff , thank you for the great and in-depth guide about translations, it's good to know how the different components interact.
So far, I've only tried the "simplest method", setting `GENERATE_LANGUAGE_FILES = true` in [JASP-Desktop/JASP-Desktop.pro](https://github.com/jasp-stats/jasp-desktop/blob/stable/JASP-Desktop/JASP-Desktop.pro#L4) and building my branch, and I see that the Dutch files get refreshed, but nothing happens regarding German. Could it be necessary to also include equivalent lines about the `*_nl.po`-files, like lines [180](https://github.com/jasp-stats/jasp-desktop/blob/stable/JASP-Desktop/JASP-Desktop.pro#L180) and [186](https://github.com/jasp-stats/jasp-desktop/blob/stable/JASP-Desktop/JASP-Desktop.pro#L186), etc?  
Maybe also my build environment is messed up, it's hard to differentiate on my end - if you find the time to build this PR's branch and confirm it works, would be immensely helpful to me...

I'll try the manual method to generate the files soon as well.

**Comment by FransMeerhoff** [comment]
HI @JoKeyser 
Thanks for trying this out so quick, and indeed find this flaw so quick. I have to make some adjustments to this .pro file or find another simple solution for that. For the moment it is only possible for you to run the lrelease from a terminal and and copy the generated ,qm file to a JASP installation.

**Comment by JoKeyser** [comment]
@FransMeerhoff okay thank you for checking it so quickly as well, that's good to know. I'll try the other method in the meantime, no worries.

**Comment by boutinb** [comment]
@FransMeerhoff But copying in the pro file the lines of the dutch translations into a german version could be a solution, no?

**Comment by FransMeerhoff** [comment]
Hi @JoKeyser 

If you have time you could try the next:
I have updated the JASP-Desktop.pro in the attached file. Could you copy this file to your local system. To use it properly you should make a change in your build environment: project -> Build Settings-> Build Environment > add
TARGET_LANGUAGE_CODE=de

Screen Shot 2020-04-23 at 10 53 04

Could you check if this solution works for you (after rebuilding the JASP-Desktop) and if so, do you think this will be a feasible solution?

[JASP-Desktop-pro.zip](https://github.com/jasp-stats/jasp-desktop/files/4522725/JASP-Desktop-pro.zip)

**Comment by FransMeerhoff** [comment]
Hi @JoKeyser 

If you have time you could try the next:
I have updated the JASP-Desktop.pro in the attached file. Could you copy this file to your local system. To use it properly you should make a change in your build environment: project -> Build Settings-> Build Environment > add
TARGET_LANGUAGE_CODE=de

Screen Shot 2020-04-23 at 10 53 04

Could you check if this solution works for you (after rebuilding the JASP-Desktop) and if so, do you think this will be a feasible solution?

[JASP-Desktop-pro.zip](https://github.com/jasp-stats/jasp-desktop/files/4522725/JASP-Desktop-pro.zip)

**Comment by FransMeerhoff** [comment]
Hi @JoKeyser 

If you have time you could try the next:
I have updated the JASP-Desktop.pro in the attached file. Could you copy this file to your local system. To use it properly you should make a change in your build environment: project -> Build Settings-> Build Environment > add
TARGET_LANGUAGE_CODE=de

Screen Shot 2020-04-23 at 10 53 04

Could you check if this solution works for you (after rebuilding the JASP-Desktop) and if so, do you think this will be a feasible solution?

[JASP-Desktop-pro.zip](https://github.com/jasp-stats/jasp-desktop/files/4522725/JASP-Desktop-pro.zip)

**Comment by FransMeerhoff** [comment]
Hi @JoKeyser 

If you have time you could try the next:
I have updated the JASP-Desktop.pro in the attached file. Could you copy this file to your local system. To use it properly you should make a change in your build environment: project -> Build Settings-> Build Environment > add
TARGET_LANGUAGE_CODE=de

Screen Shot 2020-04-23 at 10 53 04

Could you check if this solution works for you (after rebuilding the JASP-Desktop) and if so, do you think this will be a feasible solution?

[JASP-Desktop-pro.zip](https://github.com/jasp-stats/jasp-desktop/files/4522725/JASP-Desktop-pro.zip)

**Comment by FransMeerhoff** [comment]
Hi @JoKeyser 

If you have time you could try the next:
I have updated the JASP-Desktop.pro in the attached file. Could you copy this file to your local system. To use it properly you should make a change in your build environment: project -> Build Settings-> Build Environment > add
TARGET_LANGUAGE_CODE=de

Screen Shot 2020-04-23 at 10 53 04

Could you check if this solution works for you (after rebuilding the JASP-Desktop) and if so, do you think this will be a feasible solution?

[JASP-Desktop-pro.zip](https://github.com/jasp-stats/jasp-desktop/files/4522725/JASP-Desktop-pro.zip)

**Comment by FransMeerhoff** [comment]
Hi @JoKeyser 

If you have time you could try the next:
I have updated the JASP-Desktop.pro in the attached file. Could you copy this file to your local system. To use it properly you should make a change in your build environment: project -> Build Settings-> Build Environment > add
TARGET_LANGUAGE_CODE=de

Screen Shot 2020-04-23 at 10 53 04

Could you check if this solution works for you (after rebuilding the JASP-Desktop) and if so, do you think this will be a feasible solution?

[JASP-Desktop-pro.zip](https://github.com/jasp-stats/jasp-desktop/files/4522725/JASP-Desktop-pro.zip)

**Comment by JoKeyser** [comment]
@FransMeerhoff thanks a lot, that did the trick, the files get generated and I can select the translation! (I also had to get rid of a few malformed translated lines). See the screenshot above for "proof" :).

One minor complaint: The `.po` file gets edited during build, adding local paths everywhere, like this:

```
#: /home/jo/git/jasp-desktop/Docs/development/jasp-qml-style-example.qml:49
 msgctxt "jasp-qml-style-example|"
 msgid "Variables"
 msgstr "Variablen"
```

Is it possible to avoid this with more/different settings? (It's not urgent/important though, I can also just `git restore` after a build...)

**Comment by JoKeyser** [comment]
Sorry for the noise, I've decided to clean up the growing mess by replacing all changes into one new commit, based on `stable`. From now I'll try to `rebase` to avoid messy merge-commits :).

**Comment by JoKeyser** [comment]
@FransMeerhoff, @boutinb ,

I feel I reached a state that could be reasonably merged now, although it's still not complete. I feel the initial translations of `JASP-Desktop/po/jasp_de.po` and `JASP-Engine/JASPgraphs/po/R-de.po` are both at 99%, and `JASP-Engine/JASP/po/R-de.po` is more than halfway done.
They are caught up with their respective `nl` versions, i.e. they contain the same set of `msgid`s, and should no longer contain Dutch strings that could throw off other translators (instead, the strings are blank now).

I'm mentioning this also because I saw that Weblate may be on the horizon (#4213), which would be awesome. In case that's coming soon, please merge my current files as the starting point for German, to avoid duplicate work.

I'm planning to keep translating, and I guess it will take a couple more weeks for me to finish the remaining file on my own. But even when I reach that, it's of course not really "finished", so I feel the current state might as well already be used as a useful starting point.

**Comment by FransMeerhoff** [comment]
Hello @JoKeyser 

I think we should merge your PR. 
You are then able to use Weblate, to continue with your translations.
And we can test then how this works 
It do not see any harm that can be caused. 
The German translation will be available  when we activate it in the JASPDesktop configuration file.
So we can decide that afterwards, but if it's in 0.14 (+/- half september)  it would be very nice!

Do you agree on this?

Cheers Frans

**Comment by JoKeyser** [comment]
Dear @FransMeerhoff , yep that sounds like a good plan to me.
I'll gladly try Weblate in the future.
Would be awesome to hit 0.14, maybe with Weblate others join as well :).

**Comment by JoKeyser** [comment]
@FransMeerhoff, I've synced up with `stable`'s NL versions again by removing the corresponding `msgid`s, should now be good to be merged.
I suggest to squash the commits when merging.

**Pull request merged**
