### PR TITLE
Datasets: use , rather than ; to separate entries in `BFI Network.csv`

### PR DESCRIPTION
**Pull request by vandenman**
development:

image

After this PR:

image

It might be worthwhile to check all CSV files once more to assert they actually use commas and no semicolons...

if you prefer I can do that and add any changed files to this PR (I just happened to stumble upon this one).

### CODE REVIEW

**Comment by amirmasoudabdol** [comment]
Good catch! I'm in favour of this! Do it! 👍🏼

**Review by amirmasoudabdol — APPROVED** [review]

**Comment by vandenman** [comment]
For future reference, this script can be used to quickly update everything:

```r
root <- "~/github/jasp-desktop/Resources/Data Sets/Data Library"
csvFiles <- list.files(root, pattern = "\\.csv$", recursive = TRUE, full.names = TRUE)

usesSemicolons <- function(lines) {
  noCommas     <- sum(count.fields(textConnection(lines), sep = ","))
  noSemicolons <- sum(count.fields(textConnection(lines), sep = ";"))
  return(noCommas < noSemicolons)
}

for (file in csvFiles) {
  lines <- readLines(file, n = 5)
  if (usesSemicolons(lines)) {
    cat(sprintf("file %s uses semicolons! The first 5 rows are", file))
    cat(lines, sep = "\n")
    dat <- read.csv2(file, check.names = FALSE)
    write.csv(dat, file = file, row.names = FALSE, quote = FALSE)
  }
}
```

**Comment by vandenman** [comment]
@boutinb and @JorisGoosen why all the force pushes :open_mouth:

**Comment by JorisGoosen** [comment]
> @boutinb and @JorisGoosen why all the force pushes 😮

because `development` is based on `stable` so whenever that gets updates a force push is necessary to get `development` tracking that.

**Comment by vandenman** [comment]
@JorisGoosen isn't there a better way to do this? Like backporting or merging? Perhaps we should discuss that in a Tuesday meeting once?

**Comment by JorisGoosen** [comment]
> @JorisGoosen isn't there a better way to do this? Like backporting or merging? Perhaps we should discuss that in a Tuesday meeting once?

We can definitely talk about it next tuesday, wait no, next week tuesday. But also, is there some problem with the force-pushes? the commit history is still fine right?

**Comment by vandenman** [comment]
> But also, is there some problem with the force-pushes?

Yes, see for example, https://github.com/jasp-stats/jasp-desktop/pull/4667

There were no conflicts. Now, after all the force pushes, there are conflicts. It's a bit tedious for everybody who has an open PR that they need to rebase/ recreate their PR whenever you force push to development. If you look at the number of conflicts, I basically have to cherry-pick the commits to a new branch and remake the PR...

**Comment by JorisGoosen** [comment]
> > But also, is there some problem with the force-pushes?
> 
> Yes, see for example, #4667
> 
> There were no conflicts. Now, after all the force pushes, there are conflicts. It's a bit tedious for everybody who has an open PR that they need to rebase/ recreate their PR whenever you force push to development. If you look at the number of conflicts, I basically have to cherry-pick the commits to a new branch and remake the PR...

Aah yeah that looks messed up for sure... And rebasing it doesn't help?
If the merging works better (or backporting, but that would also get quite messy) we can look at that.

**Comment by vandenman** [comment]
> Aah yeah that looks messed up for sure... And rebasing it doesn't help?

Rebasing might fix it, but I got a bunch of merge conflicts so I abandoned the rebase and will just create a new PR instead.

**Comment by JorisGoosen** [comment]
> > Aah yeah that looks messed up for sure... And rebasing it doesn't help?
> 
> Rebasing might fix it, but I got a bunch of merge conflicts so I abandoned the rebase and will just create a new PR instead.

So that sounds like this branch was kind of messed up to begin with right?
As in, it was including stuff that didnt belong in here?
Anyway, it seems merged already? so lets discuss it further later.

**Comment by JorisGoosen** [comment]
Yeah of course im looking at this PR.. never mind that remark...

**Comment by vandenman** [comment]
> So that sounds like this branch was kind of messed up to begin with right?

The branch was before the CMake transition, so stuff needed to be changed anyway.

> As in, it was including stuff that didnt belong in here?

I didn't commit anything that didn't need to be there, but I guess because of rebase & force push there were commits in there that are no longer in development. If you look at https://github.com/jasp-stats/jasp-desktop/pull/4734 then I only added one commit (minimal working example), yet there are multiple other commits listed.

**Comment by vandenman** [comment]
also @JorisGoosen, have fun rebasing https://github.com/jasp-stats/jasp-desktop/pull/4726 :stuck_out_tongue:

**Pull request merged**
