### PR TITLE
list dependent in a table output

### PR DESCRIPTION
**Pull request by Kucharssim**
solves https://github.com/jasp-stats/jasp-issues/issues/582 for:

- linear regression
- logistic regression
- bayesian linear regression

### CODE REVIEW

**Comment by TimKDJ** [comment]
Can you solve the conflicts?

**Comment by TimKDJ** [comment]
Another conflict?

**Comment by Kucharssim** [comment]
@TimKDJ The test failed because of the bayesian correlations, should I just rebase?

**Comment by TimKDJ** [comment]
Yes I fixed that

**Comment by Kucharssim** [comment]
I screw up rebasing/merging, I’ll make a fresh PR

**Pull request closed without merging**
