### PR TITLE
Add constants to LDA coefficients table

### PR DESCRIPTION
**Pull request by koenderks**
As requested in https://github.com/jasp-stats/jasp-issues/issues/575

### CODE REVIEW

**Comment by koenderks** [comment]
Weirdly enough, the unit tests do not fail on my machine...

**Comment by boutinb** [comment]
@koenderks Do we use the right package?

**Comment by koenderks** [comment]
I believe so. The unit tests only fails for 4 plots (in which the axis is different)? Could it be a different version of JASPgraphs?

**Comment by boutinb** [comment]
@koenderks Do you know why Travis still fails

**Comment by koenderks** [comment]
No

**Comment by TimKDJ** [comment]
If you don't change the .svg files then there is no problem for me.

I use these versions, do they differ for you?
> packageVersion('JASPgraphs')
[1] ‘0.4.3’
> packageVersion('jasptools')
[1] ‘0.8.4’
> packageVersion('jaspResults')
[1] ‘1.12’

**Pull request merged**
