### PR TITLE
[DO NOT MERGE] AF remaining features

### PR DESCRIPTION
**Pull request by Janto91**
This adds the remaining features from the Field list for Anova, Ancova, RM Anova, and logistic regression. However, there is some work on the code needed to get JASP running with these new features. The code also needs to be thoroughly tested and cross-checked with SPSS (see the Excel sheet I shared) before this can be merged.

### CODE REVIEW

**Comment by TimKDJ** [comment]
@Kucharssim: so are all the changes of this PR incorporated now?

**Comment by Kucharssim** [comment]
@TimKDJ not yet, two more PRs to come, but for that we need to merge @JohnnyDoorn work first (https://github.com/jasp-stats/jasp-desktop/pull/3093)

**Comment by Kucharssim** [comment]
This can be closed now.

**Comment by TimKDJ** [comment]
Well done!

**Pull request closed without merging**
