### PR TITLE
Fixed the font size of saved images

### PR DESCRIPTION
**Pull request by TimKDJ**
It only works for ggplot objects; qgraph and base plots are still not ok. Hopefully those plots will be rewritten to ggplot soon, as I do not have a good solution for them.

Also I I did not include the tiff rescaling, as it only seemed to screw with the dimensions. @vankesteren: I think you wrote this code; why does tiff need rescaling, but not the other formats?

This PR still needs to be thoroughly tested on other platforms.

### CODE REVIEW

**Comment by vankesteren** [comment]
I think when I wrote this code I was just programming by trial-and-error because this stuff is quite obscure.

**Comment by vankesteren** [comment]
from memory: maybe because I was setting a specific resolution for tiff?

**Comment by AlexanderLyNL** [comment]
Hi @akashrajkn @astefan1 @Kucharssim. Could you guys checkout this PR and see how this works on your OS?

**Comment by Kucharssim** [comment]
On MacOS High Sierra 10.13.6 it works perfectly.

**Pull request merged**
