### PR TITLE
Removed all the "f" added at the end of optionnames in ReliabilityFreq

### PR DESCRIPTION
**Pull request by JorisGoosen**
- Why were they there anyway?
- Fixes https://github.com/jasp-stats/jasp-test-release/issues/890 (upgrader for reliability)

### CODE REVIEW

**Comment by TimKDJ** [comment]
@juliuspf any reason in particular the added `f`'s were there?

**Comment by TimKDJ** [comment]
@JorisGoosen: Even if it is not necessary it might not be nice to make these changes, because all the references to these option names also need to be changed in the R files

**Comment by JorisGoosen** [comment]
Ooh yeah right... Its just because in the bayesian QML they were all without the "f"'s.
I will just also change them in the R code then.

They just don't make sense.

Unless @juliuspf has a really good reason for them?

**Comment by juliuspfadt** [comment]
Well, embarrassingly enough I had the f's in there to avoid name clashes with the Bayesian file, because in a previous version both analysis were part of one R-file. There is no more meaningful reason, you can easily remove them.

**Review by TimKDJ — APPROVED** [review]

**Pull request merged**
