### PR TITLE
ANOVA (added name dependent variable in title )

### PR DESCRIPTION
**Pull request by raviselker**
For both the ANOVA and ANCOVA table

### CODE REVIEW

**Comment by jonathon-love** [comment]
how would you feel about something a bit more minimalist?

rather than

`ANOVA (Dependent Variable: *Intelligence*)`

Perhaps just:

`ANOVA - Intelligence`

**Comment by raviselker** [comment]
I think it should be clear that it refers to the dependent variable, but I could make it a little more mimimalist:

ANOVA (Dependent: *Intelligence*)

**Comment by jonathon-love** [comment]
For the person doing the analysis, the very minimalist will be clear that it refers to the dependent (because they dragged it into the dependent box after all).
If you were working with some colleagues on a particular dataset, it would be clear if you sent them the very minimalist table that that was the dependent.
I think it would only be unclear to someone unfamiliar with the data, and perhaps unfamiliar with the design - but in this case, a person would provide a figure caption anyway.
My thinking with putting it in the title, is for if you open up some old results. you may have run two similar analyses with similar dependents - this lets you tell which is which at a glance, without having to open the options dialog.
I just think the really minimalist looks really good; whereas the less minimalist is a bit busy.
Granted, we're on shaky, not-so-object ground.

what do you think?

**Comment by raviselker** [comment]
I agree

**Pull request merged**
