### PR TITLE
Created Unit Test for AnovaRepeatedMeasures

### PR DESCRIPTION
**Pull request by Kucharssim**

### CODE REVIEW

**Comment by vankesteren** [comment]
Your new unit tests actually fail! Any idea why?

You can see the result [here](https://travis-ci.org/jasp-stats/jasp-desktop/builds/353090252#L1323)

**Comment by Kucharssim** [comment]
The unit test does work on my computer.  
After consulting Bruno, it seems that the jasptools::run() cannot load other dataset than 'test.csv'. I'll try a workaround by creating the test datasets directly in the script - if it passes, at least we know it's because of this.

**Comment by vandenman** [comment]
I tried the tests myself and they pass on windows but fail on Linux. After closer inspection of the error message, I got:


This analysis terminated unexpectedly.<br><br>Error in ref.grid(object = structure(list(anova_table = structure(list(: Can't handle an object of class  “afex_aov” <br> Use help('models', package = 'lsmeans') for information on supported models.<br><br>

This appears related to #2412, perhaps @JohnnyDoorn knows more about it? Anyway, the tests themselves look fine but I suggest putting this PR on hold until the other bug has been fixed.

**Comment by JohnnyDoorn** [comment]
yay =)

**Comment by Kucharssim** [comment]
Thanks, Johnny!

Let me revert to the version with loading the datasets - now it creates the data in the script, which makes the test slower.

**Comment by Kucharssim** [comment]
Huh, now the RM ANOVA unit test works, but it somehow broke the principal component analysis? Everything is fine on Windows though, again...

**Comment by JohnnyDoorn** [comment]
Hmm the PCA check also succeeds for me on Ubuntu 16.04. 
Here is the Travis output for the failed test:
test-principalcomponentanalysis.R:58: failure: Factor correlation table matches
`test` not equal to `ref`.
Length mismatch: comparison on first 2 components

**Comment by JohnnyDoorn** [comment]
Try 2: yay??

**Pull request merged**
