### PR TITLE
Added some ind. T test effect sizes

### PR DESCRIPTION
**Pull request by bramotten**
Implementation is practically the same as https://cran.r-project.org/web/packages/effsize/index.html. I can figure out how to add some tests, but would then still rely on the correctness of that package.

### CODE REVIEW

**Comment by boutinb** [comment]
@bramotten Sorry, there is a conflict: the TTestIndependantSamples.qml file has been moved to Resources/T-Tests/qml/TTestIndependentSamples.qml. Can you rebase your repository and solves this problem? If you push (with --force) your changes, your Pull Request will be automatically updated.

@JohnnyDoorn Can you review this PR?

**Comment by AlexanderLyNL** [comment]
@bramotten Just to make things clear for me, what's the main difference between the output of effsize and the code you implemented (from what I see it's custom code)? If there's no difference, is there a specific reason why you'd prefer your custom code over that of the effsize package?

**Comment by boutinb** [comment]
There is a conflict on this PR. Should this be implemented for the release?

**Comment by JohnnyDoorn** [comment]
@bramotten  can you update your file with the removed "else"s? Then we can merge this into the main branch and have it in the next release =)

**Comment by AlexanderLyNL** [comment]
I don't want this in the coming release, before it's being checked properly. So this can wait.

**Comment by boutinb** [comment]
@bramotten There are still conflicts!

**Comment by boutinb** [comment]
@bramotten We may add this PR now. But there is still a conflict. Can you solve it?

**Comment by JohnnyDoorn** [comment]
Can this be added now?

**Comment by AlexanderLyNL** [comment]
Can the unit tests and the documentation be updated as well?

**Comment by JohnnyDoorn** [comment]
When it's merged I will add the unit tests and help-files (think that's a bit faster and then it's finished for the next release).

**Pull request merged**
