### PR TITLE
Show the right implicit empty values in tooltip

### PR DESCRIPTION
**Pull request by boutinb**
If you set a nominal or ordinal variable in a scale VariablesList, a tooltip tells you how the values are transformed into scale. It gives also a list of 'implicit' empty values: that is the not empty values that could not be converted into a double value. This list was not correct, it gave all the convertable values.

### CODE REVIEW

**Comment by JorisGoosen** [comment]
Could you give me an example of the problem and how this solves it?
Because Ive been looking in my nightly for weird tooltip with "wrong" info and cant see it?

**Comment by boutinb** [comment]
This is what I got with this test:
Screenshot 2024-11-28 at 12 11 57

**Comment by boutinb** [comment]
And this is what I get after my fix:
Screenshot 2024-11-28 at 12 14 52

**Comment by boutinb** [comment]
Here are my file: 
[simple.csv](https://github.com/user-attachments/files/17947451/simple.csv)

**Comment by JorisGoosen** [comment]
@boutinb I think the double check should be on the value, not the label.

**Pull request merged**
