### PR TITLE
improved fit measures for confirmatory factor analysis

### PR DESCRIPTION
**Pull request by vankesteren**

### CODE REVIEW

**Comment by boutinb** [comment]
Sorry Erik-Jan, I have just changed the ConfirmatoryFactorAnalysis.qml file, and you have now a conflict... Should this PR be in the release?

**Comment by vankesteren** [comment]
@boutinb I'm not sure what to do with the `columns: 1` argument. Does it replace the `ColumnLayout`? I made some minor changes in the QML: it now has only the "additional fit measures" option instead of all those aic, bic, etc options.

**Comment by vankesteren** [comment]
look, this is the only change in the QML:
https://github.com/jasp-stats/jasp-desktop/pull/3397/files?file-filters%5B%5D=.qml

**Comment by vankesteren** [comment]
branch can be merged!

**Pull request merged**
