### PR TITLE
Added upgrade options for Reliability

### PR DESCRIPTION
**Pull request by JorisGoosen**
- Implements https://github.com/jasp-stats/INTERNAL-jasp/issues/915
- Also made the Reliability conform to the qml styleguide because they were a mess
- Updated JASPs version to 0.13

### CODE REVIEW

**Review by vandenman — APPROVED** [review]
So I can't really judge upgrades.json but the rest looks good to me

**Comment by vandenman** [comment]
unit tests fail because of MixedModelsBGLMM btw

**Comment by TimKDJ** [comment]
> So I can't really judge upgrades.json but the rest looks good to me

You can test it by loading an old Reliability .jasp file into JASP. If that works then it should be good (maybe you already did this)

**Comment by boutinb** [comment]
> > So I can't really judge upgrades.json but the rest looks good to me
> 
> You can test it by loading an old Reliability .jasp file into JASP. If that works then it should be good (maybe you already did this)

I just test it. It seems to work.

**Comment by JorisGoosen** [comment]
Yeah, so I had kind of hoped that @vandenman would take a look at the renames in the upgrades.
Every `"blabla": { "_renamed": "oldBlabla" }` denoted an instance of oldBlabla being renamed to blabla.

Because just loading an old Reliability will work fine, but maybe some options are not correct... Which I think is important.

**Comment by vandenman** [comment]
@JorisGoosen Ok I'll give that a try

**Comment by vandenman** [comment]
Everything seems to work as intended.

**Comment by JorisGoosen** [comment]
Ok good!

**Comment by JorisGoosen** [comment]
Then Ill just add the last few changes by @juliuspf in https://github.com/jasp-stats/INTERNAL-jasp/issues/916

**Pull request merged**
