### PR TITLE
JASPWidgets["title"] does not exist anymore

### PR DESCRIPTION
**Pull request by boutinb**
Solves jasp-stats/jasp-test-release#1380
Solves jasp-stats/jasp-test-release#1379
Solves jasp-stats/jasp-test-release#1377
Solves jasp-stats/jasp-test-release#1371

I'm not at all sure if this is the right thing to do! 
I just saw that the "title" type is called and that JASPWidgets does not have this type....

### CODE REVIEW

**Comment by JorisGoosen** [comment]
But this "title" thing isn't called for newer files right?

So shouldn't we update the incoming "wrong" data then? Instead of changing the javascript?

**Comment by boutinb** [comment]
> But this "title" thing isn't called for newer files right?

Apparently, but I could not see in the log when this has happened, so I wondered if you or @TimKDJ knew why this has changed.

**Comment by JorisGoosen** [comment]
Hmm, well, I will have a look at the original issue later and see what I think of it.

**Comment by JorisGoosen** [comment]
Well, it solves the problem and after refreshing in the 0.15 version it also works without the fix so this is good to go.

**Review by JorisGoosen — APPROVED** [review]

**Comment by JorisGoosen** [comment]
I am adding a comment though

**Pull request closed without merging**
