### PR TITLE
Inclusion probabilities for matched models

### PR DESCRIPTION
**Pull request by TimKDJ**
Adds an option to perform a targeted inclusion analysis for Bayesian (RM) AN(C)OVA. See also https://www.cogsci.nl/blog/interpreting-bayesian-repeated-measures-in-jasp

Additionally I
- removed stepwise code (no longer used)
- made style changes

### CODE REVIEW

**Comment by quentingronau** [comment]
I checked this for an example by hand and the numbers matched quite well (only the third decimal was different but this may be due to rounding), so I think this is fine.

Cheers,
Quentin

**Comment by TimKDJ** [comment]
@quentingronau also add the if > 1 = 1 and < 0 = 0?

**Comment by quentingronau** [comment]
Yes, that is probably a good idea.

**Comment by TimKDJ** [comment]
Alright, guess it's good then

**Comment by quentingronau** [comment]
Yes, great.

**Pull request merged**
