### PR TITLE
dependencies: upgrade marked.js to fix markdown render

### LINKED ISSUE #2847: [Bug]: Strange formatting of text in the help box in the logistic regression module
### JASP Version

0.19.0

### Commit ID

_No response_

### JASP Module

Regression

### What analysis are you seeing the problem on?

Logistic regression

### What OS are you seeing the problem on?

Windows 10

### Bug Description

There is a very strange formatting of the text (different font size) in the help box in the logistic regression module. See screen shot:
Skärmklipp logistic

### Expected Behaviour

Same formatting as in all other info boxes for different analysis.

### Steps to Reproduce

1. No
2.
3.
...

### Log (if any)

_No response_

### More Debug Information

_No response_

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

### PR DESCRIPTION
**Pull request by shun2wang**
Fix: https://github.com/jasp-stats/jasp-issues/issues/2847

It's a bug of [marked.js](https://marked.js.org/) and was fixed from [v5.0.4](https://github.com/markedjs/marked/releases/tag/v5.0.4)  so let's just upgrade it.

### CODE REVIEW

**Comment by boutinb** [comment]
This does not fix the issue, but it is still a good thing to update the marked.js

**Review by boutinb — APPROVED** [review]

**Comment by shun2wang** [comment]
I can reproduce it on marked.js 5.0.3 but not 5.0.4 or later on their demo page.

**Comment by shun2wang** [comment]
image
image

Yes the origin markdown code in our repo has a space not a newline(see:https://github.com/jasp-stats/jaspRegression/blob/92e7db0c5e6a9e1c5ea50a7fc854305b2c75ab9a/inst/help/RegressionLogistic.md?plain=1#L3 ) but that's about https://github.com/markedjs/marked/commit/efc40dfb05b4b75fd8cab93926aa7aac08738380 fix from markdown files was not robust so I fix it by Js parser side.

Maybe you might be caught by the build cache I guess, because our build sometimes doesn't update the js code immediately, you can check your `Resources/Help/marked.js` folder to confirm this:-)

**Comment by boutinb** [comment]
Hmm, strange. I could fix the issue by removing some spaces https://github.com/jasp-stats/jaspRegression/commit/f8484ee8e4c52522d750690a8297c37d1bda468a

**Comment by shun2wang** [comment]
which version of marked.js in your built path 'Resources/Help/marked.js', anyway both fix are OK but your build dir may not updated I guess😀

**Pull request merged**
