### PR TITLE
Bugfix: make LaTeX formula editable

### PR DESCRIPTION
**Pull request by shun2wang**
Fixes https://github.com/jasp-stats/INTERNAL-jasp/issues/2333 and https://github.com/jasp-stats/INTERNAL-jasp/issues/2360

- Now can update the LaTex annotations.

### CODE REVIEW

**Comment by JorisGoosen** [comment]
Oh sorry @shun2wang you'll have to rebase this on `upstream/development`

**Comment by shun2wang** [comment]
Ok, these will not in this relese, I will rebase again.

**Comment by JorisGoosen** [comment]
> Ok, these will not in this relese, I will rebase again.

This change shouldnt be in the new release?

**Comment by shun2wang** [comment]
This fix is indeed ready for review, but given that we're testing version 0.18 right now almost complete, I'm not sure if it should get into?

**Comment by JorisGoosen** [comment]
> This fix is indeed ready for review, but given that we're testing version 0.18 right now almost complete, I'm not sure if it should get into?

Yeah maybe you are right, I find it hard to see whether this will be a problematic change or not.
And anyway, we'll probably have a release quite soon afterwards

**Review by JorisGoosen — APPROVED** [review]

**Comment by JorisGoosen** [comment]
it works fine and I think it cant hurt to merge this now

**Pull request merged**
