### PR TITLE
Font from Preferences should be used in Dynamic Module console, Welcome Page and About Box

### PR DESCRIPTION
**Pull request by boutinb**
Fixes jasp-stats/jasp-test-release#1009

### CODE REVIEW

**Comment by JorisGoosen** [comment]
Welcome page looks great!

Aboutbox wasn't made for scaling though:
image

**Comment by JorisGoosen** [comment]
Could you also fix the weird "Modul installieren" button:
image

Like the size of the buttons changes all the time depending on zooming in/out...
Zooming out, then in again I get: (after switch to english):
image

Zoom out
image

Zoom in 
image

**Comment by JorisGoosen** [comment]
Aah and the module installer now looks great, except for the fact that when you zoom in a lot the text doesn't fit anymore in the popup and there is no scrollbar.

I guess it would be nicer if it didn't always just take to the middle segment of the screen but has a minimum size and adds a scrollbar but that might very well be out of scope for this PR?

Normal zoom looks awesome:
image

Bit hard to read all:
image

Not that bad actually, just leave that I guess we can do it later?

**Comment by boutinb** [comment]
The Module Install button problem was due to a binding loop, which is now solved.
The Module Installer console can be in the next release reshaped (when it will be really used).

**Pull request merged**
