### PR TITLE
RM ANOVA plot: apply within-participants normalization for CI descriptives

### PR DESCRIPTION
**Pull request by JohnnyDoorn**
This was missed in the rewrite (see https://forum.cogsci.nl/discussion/comment/20069#Comment_20069)

### CODE REVIEW

**Comment by vandenman** [comment]
So the changes look fine but, to avoid this from happening again, could you add a unit test?

**Comment by JohnnyDoorn** [comment]
@vandenman Great idea, just added it!

**Comment by JohnnyDoorn** [comment]
I also added a small fix for https://github.com/jasp-stats/jasp-issues/issues/918 here (Adding a conditional before extracting the rror message), since it is very minor

**Review by vandenman — APPROVED** [review]

**Comment by vandenman** [comment]
IMO this can be merged.

**Comment by AlexanderLyNL** [comment]
@TimKDJ how do I check whether this is in stable already or not?

**Comment by TimKDJ** [comment]
Well you were the one that merged it into stable...

Schermafbeelding 2020-08-14 om 08 57 58

(right above your own comment in this pr)

Or do you mean whether it's in the module? 
For an ANOVA it should be here: https://github.com/jasp-stats/jaspAnova/pulls

**Pull request merged**
