### PR TITLE
Fix bug in benfords law

### LINKED ISSUE #815: Audit Module: check the frequency of last digits
* Enhancement: in addition to Benford's law, it would be useful to check the frequency of last digits.
* Purpose: Improve fraud detection.
* Use-case: Example: http://datacolada.org/77

Thanks!

### PR DESCRIPTION
**Pull request by koenderks**
Make sure last numbers are read in correctly.

Fixes https://github.com/jasp-stats/jasp-issues/issues/815

[testfile.zip](https://github.com/jasp-stats/jasp-desktop/files/4911304/testfile.zip)

Accompanied by https://github.com/jasp-stats/Audit/pull/10

### CODE REVIEW

**Comment by JorisGoosen** [comment]
Nitpicky but: if you choose first & second digit the table still says "Leading digit":
Schermafbeelding 2020-07-13 om 12 50 02

**Comment by JorisGoosen** [comment]
And Im still a bit confused why in a number like "123.0123" the first digit wouldn't be 0?
Especially in uniform distribution?

Or do you always skip that one?
Because the percentages you give here wouldn't make a lot of sense:
Schermafbeelding 2020-07-13 om 12 52 34

**Comment by JorisGoosen** [comment]
For the rest this all looks fine!

**Comment by koenderks** [comment]
> And Im still a bit confused why in a number like "123.0123" the first digit wouldn't be 0?
> Especially in uniform distribution?
> 
> Or do you always skip that one?
> Because the percentages you give here wouldn't make a lot of sense:
> Schermafbeelding 2020-07-13 om 12 52 34

Actually, the first digit would be a 1 in this instance right?

Thanks for the nitpicky part, I'll adjust that in just a minute.

Furthermore, I always just ignore the 0 as a starting digit. Then it will just be the second number.

**Comment by AlexanderLyNL** [comment]
I'm still concerned with Benford's law for the last digit, if it ends with a zero.

**Comment by JorisGoosen** [comment]
Well, I'll leave the number interpretations and zeroes up to @koenderks and @AlexanderLyNL .
If you both think the current approach (or after fixes) is ok this PR can be merged.

**Comment by koenderks** [comment]
Yes, it should probably count the last digit that is not zero.

**Comment by AlexanderLyNL** [comment]
> Yes, it should probably count the last digit that is not zero.

Should, or is? What does the Benford's law for last digit procedure do for entries of the form shown below?

`4.60, 5.70, 12.10, 32.99`

**Comment by koenderks** [comment]
image

**Comment by AlexanderLyNL** [comment]
Seems to work well then. So for `4.60` it just studies `6`, which is great. I'm not sure whether Benford's law is reasonable for last digits, though, but that's a different discussion. If people want to study Benford's law for last digit, then so be it.

**Comment by koenderks** [comment]
I think they mostly want to compare the distribution of last digits to a uniform distribution, hence the inclusion of that in this PR.

**Pull request merged**
