### PR TITLE
Selection analysis for audit module

### PR DESCRIPTION
**Pull request by koenderks**
Implements a separate selection analysis for the audit module for the next version, basically extracting the selection parts from the workflow and putting them in a separate analysis. 

@JorisGoosen can this PR be done at this branch?

### CODE REVIEW

**Comment by JorisGoosen** [comment]
Could you switch it to the stable branch?

**Comment by JorisGoosen** [comment]
And you forgot to update `description_nl.json`

**Comment by koenderks** [comment]
Yes, done!

**Comment by JorisGoosen** [comment]
Ooh hey, zou je deze aanpassingen ipv op jasp-desktop ook op https://github.com/jasp-stats/Audit kunnen doen?
Dan kunnen we de aanpassingen aan analyses ed los houden van aanpassingen aan JASP ^^

**Comment by JorisGoosen** [comment]
I will check out the weird issue with the errormsg from here though.

**Comment by JorisGoosen** [comment]
Or well, Ill check your code, make sure the errormsg shows up and if its all okay I will merge into https://github.com/jasp-stats/Audit for you instead of here.

**Pull request merged**
