### PR TITLE
About Box should use the right fonts and be resizable.

### PR DESCRIPTION
**Pull request by boutinb**
Fixes https://github.com/jasp-stats/INTERNAL-jasp/issues/1458: it uses the user selected font and it is also zoomable.
I'm not expert in APA rules, but the citation in the About box is the same as in https://jasp-stats.org/faq/how-do-i-cite-jasp/, so I'm not sure what is wrong here. @vandenman do you know this?

### CODE REVIEW

**Comment by vandenman** [comment]
The citation is fine. I did notice two weird things though:

1. Zooming out keeps the window size but adds empty white space: 
image
2. Zooming in resizes the window if it doesn't fit.

**Comment by boutinb** [comment]
Hmm I don't get this problem on Mac. Did this problem exist also on 0.15?

**Comment by boutinb** [comment]
Also fixes https://github.com/jasp-stats/INTERNAL-jasp/issues/738

**Comment by vandenman** [comment]
The problem is also there in 0.16, maybe it's a Linux thing.

**Review by vandenman — APPROVED** [review]

**Pull request merged**
