### PR TITLE
Fix https://github.com/jasp-stats/jasp-test-release/issues/675 ARM translation

### PR DESCRIPTION
**Pull request by koenderks**
Fix https://github.com/jasp-stats/jasp-test-release/issues/675

### CODE REVIEW

**Comment by JorisGoosen** [comment]
@FransMeerhoff @boutinb the newly added gettexts here will still be translated right?
As in, when new empty R.po stuff shows up before release?

Or should I add these strings manually to the Dutch Translations google doc?

**Comment by boutinb** [comment]
Koen will add the translation.

**Comment by koenderks** [comment]
Maybe it is best if this is done together will all the other missing audit translation (there are a lot).

**Comment by JorisGoosen** [comment]
Well, as long as we add them before we release.

**Comment by koenderks** [comment]
I hope the translators that we paid will do this.

**Pull request merged**
