### PR TITLE
Fix distplot issues

### PR DESCRIPTION
**Pull request by vankesteren**
This pull request fixes (hopefully) 2 things:
1. Factors now get a barplot, not a distribution plot - as they should
2. Strange resolution with odd-size displays has been fixed

The resolution error still needs to be tested on mac @boutinb

### CODE REVIEW

**Comment by AlexanderLyNL** [comment]
I've got some problems with the resolution. I tried both 72/96 and 52/96. Neither works on my mac 10.12.6

screen shot 2018-09-21 at 15 41 11

**Comment by AlexanderLyNL** [comment]
The error only occurs for scale variables and not for factors.

**Comment by vankesteren** [comment]
Let's talk about this wednesday?

**Comment by AlexanderLyNL** [comment]
We can even do it today, if you have the time, because I'm at the UU now.

**Comment by AlexanderLyNL** [comment]
Awesome works well

**Comment by vankesteren** [comment]
Don't know yet why the PR checks fail; the error seems to be in the table but I did not change anything in the table 😒

**Pull request merged**
