### PR TITLE
Fix mac x86_64 build R4.3.1

### PR DESCRIPTION
**Pull request by RensDofferhoff**
With this small change I could create this dmg:
https://static.jasp-stats.org/Nightlies/macOS-x86_64/JASP-nightly-development-0.dmg

It works for me but please test it out.

### CODE REVIEW

**Comment by JorisGoosen** [comment]
You didnt get the `fortran` problems then?
(Because I tried this out last week but couldnt build. I guess I did something wrong with the buildfolder then)

**Comment by RensDofferhoff** [comment]
Build completes and works here. Waiting to see if it also works for @boutinb now. 
https://static.jasp-stats.org/Nightlies/macOS-x86_64/JASP-nightly-stable-8daad8a8f471eca35e8090c7d27566947a6afcc4.dmg

**Comment by RensDofferhoff** [comment]
The branch I build was a little behind so lets see what happens with the currently on going build.

**Comment by boutinb** [comment]
Yes this one works! Do I have to test something specifically?

**Comment by RensDofferhoff** [comment]
> Yes this one works! Do I have to test something specifically?

Awesome!  The development build is still cooking it will be done in 20 minutes.  If you could test development modules on that one that would be great

**Review by boutinb — APPROVED** [review]

**Pull request merged**
