### PR TITLE
Update to RM ANOVA effects sizes (v2)

### PR DESCRIPTION
**Pull request by JohnnyDoorn**
Messed up my last PR, so a new one:
- Changed the qml of the Bayesian correlation to be more uniform to each other (and freq correlation), and the help files.
- Eta squared is now correct for RM ANOVA.
- Added generalized eta squared.
- Added assumption tests  and help file to MANOVA.

### CODE REVIEW

**Comment by TimKDJ** [comment]
@Kucharssim you had a look at this already, right?

**Comment by Kucharssim** [comment]
@TimKDJ not yet the MANOVA stuff until now. This will need a small revision I suppose.

@JohnnyDoorn found some bugs in the manova assumptions:
Open Erotic Pictures and Love data set (under 3. ANOVA), setup like this:
Screen Shot 2019-05-21 at 10 27 40

1) tick homogeneity of covariance matrices, results in this error:
Screen Shot 2019-05-21 at 10 31 31

2) multivariate normality gives the following table (the W statistics got lost somewhere):
Screen Shot 2019-05-21 at 10 32 44

**Comment by JohnnyDoorn** [comment]
Great catch I just updated the code and these two things should be fixed now =)

**Comment by Kucharssim** [comment]
Works nice! Assuming Travis is happy I think this PR can be merged now.

**Pull request merged**
