### PR TITLE
Shows descriptive plots Bayesian RM ANOVA

### PR DESCRIPTION
**Pull request by JohnnyDoorn**
Before you had to resize to show the plots.

### CODE REVIEW

**Comment by AlexanderLyNL** [comment]
This was fixed by Don in https://github.com/jasp-stats/jasp-desktop/pull/2811  @vandenman a different implementation?

**Comment by vandenman** [comment]
Nope I fixed the anova and ancova. Somehow this plot also needs the change. I vaguely remember that Tim made the keep redundant at one point, perhaps something changed in common and now it needs to be specified again? We should check other plots to make sure.

**Comment by AlexanderLyNL** [comment]
I checked all the plots on my branch. The only one that doesn't work is Bayesian RM ANOVA, thus, once this is done we'll have all the plots covered.

**Comment by AlexanderLyNL** [comment]
@vandenman Travis says that it's done, but github says Travis is still doing it's magic.

**Pull request merged**
