### PR TITLE
fix .msi installer: only current user can disable MS-GameDVR

### LINKED ISSUE #2841: [Bug]: Local installation not able to complete
### JASP Version

0.19.0

### Commit ID

_No response_

### JASP Module

Unrelated

### What analysis are you seeing the problem on?

_No response_

### What OS are you seeing the problem on?

Windows 10

### Bug Description

Hey JASP team, 

I was installing version 0.19 with the .msi executable. Under the "Advanced" option I selected a local account rather than system-wide installation. However, midway through I got this error message. 
error 
My Windows version is 10.0.19045, I can happily post more system info. 
Also, a system-wide installation worked fine. I was able to reproduce this error with and without JASP 0.18.3 pre-installed

### Expected Behaviour

This installation should have run.

### Steps to Reproduce

1. Download & run "JASP-0.19.0.0-Windows.msi"
2. Select Installation Scope, click Advanced
3. On Product Features, for Visual C++ 14.0 Runtime select "Entire Feature will be installed on local hard drive". Note that the installer says 0KB will be required.
4. On pop-up, select OK

image

### Log (if any)

_No response_

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

### PR DESCRIPTION
**Pull request by shun2wang**
Fix: https://github.com/jasp-stats/jasp-issues/issues/2841

People don't always have admin privileges, so let's take this action only for the current user.

Also capitalized all GUIDs, this is required by Microsoft MSI see: https://learn.microsoft.com/en-us/windows/win32/msi/guid

Can merge to another branch and make a test build let users test it.

### CODE REVIEW

**Comment by RensDofferhoff** [comment]
I will make a build to test now. Thanks!

**Comment by shun2wang** [comment]
@boutinb @RensDofferhoff so what should we do for this .msi installer as we will release hotfix soon.

**Comment by shun2wang** [comment]
I also want to migrate .msi installer to .exe installer with NSIS tools someday. any ideas?

**Comment by boutinb** [comment]
> @boutinb @RensDofferhoff so what should we do for this .msi installer as we will release hotfix soon.

We want to make a hotfix (0.19.1) with just the filter issue fix, so that we can deliver it with minimal testing. We should do that today.
We want also to make a new version (0.19.2)  in October, so that the other fixes (and new features) can be released quite quickly. This version will need more testing.

**Comment by shun2wang** [comment]
But installer related problems is more critically I think.just a suggestion.

**Comment by RensDofferhoff** [comment]
Last Time I made a build I remember there was a problem still on my machine. I will need to recheck this. 
0.19.2 will follow 0.19.1 shortly

**Comment by shun2wang** [comment]
@boutinb @JorisGoosen Dont forget this:-)  we are not deprecate `.msi` yet.

**Comment by JorisGoosen** [comment]
We can do another testbuild for sure

**Review by JorisGoosen — APPROVED** [review]

**Comment by JorisGoosen** [comment]
Or just merge it. It should be fine I think.

**Pull request merged**
