### PR TITLE
Added unit tests for the R analyses

### PR DESCRIPTION
**Pull request by TimKDJ**
This pr contains unit tests for nearly all analyses.
Excluded are (1) Bayesian linear regression (will be swapped out soon), (2) logistic regression (@vankesteren will do this) and (3) the modules.

Obviously the test suite still needs to become far more comprehensive.
Henceforth we should add test cases when bugs are solved and new features added.

Unfortunately I've been unable to get travis to install FreeType 2.8.
This means that for the time being regression tests for plots are skipped.
Hopefully we'll find a solution for this soon.

A separate PR for JASPTools will follow (which will make it easy for developers to run tests)

### CODE REVIEW

**Comment by Erik-Jan** [comment]
I have no idea what this is about.


Sincerely,


E.J. Duyvené de Wit 06-50668589 Arnhem On Thu, Nov 02, 2017 at 2:43pm, Tim de Jong < notifications@github.com [notifications@github.com] > wrote:
This pr contains unit tests for nearly all analyses.
Excluded are (1) Bayesian linear regression (will be swapped out soon), (2) logistic regression ( @Erik-Jan [https://github.com/erik-jan] will do these) and (3) the modules.

Obviously the test suite still needs to become far more comprehensive.
Henceforth we should add test cases when bugs are solved and new features added.

Unfortunately I've been unable to get travis to install FreeType 2.8.
This means that for the time being regression tests for plots are skipped.
Hopefully we'll find a solution for this soon.

A separate PR for JASPTools will follow (which will make it easy for developers to run tests)




YOU CAN VIEW, COMMENT ON, OR MERGE THIS PULL REQUEST ONLINE AT:
https://github.com/jasp-stats/jasp-desktop/pull/2115 [https://github.com/jasp-stats/jasp-desktop/pull/2115]

COMMIT SUMMARY
 * Added unit tests for the R analyses

FILE CHANGES
 * M .gitignore [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-0] (4)
 * A .travis.yml [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-1] (11)
 * M JASP-Engine/JASP/R/descriptives.R [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-2] (6)
 * M JASP-Engine/JASP/R/regressionloglinearbayesian.R [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-3] (2)
 * A JASP-Tests/R/DESCRIPTION [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-4] (12)
 * A JASP-Tests/R/tests/figs/Anova/anova-descriptives-ci.svg [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-5] (97)
 * A JASP-Tests/R/tests/figs/Anova/anova-descriptives-se.svg [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-6] (97)
 * A JASP-Tests/R/tests/figs/Anova/anova-q-q.svg [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-7] (148)
 * A JASP-Tests/R/tests/figs/BinomialTest/binomialtest-descriptives-1.svg [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-8] (42)
 * A JASP-Tests/R/tests/figs/BinomialTest/binomialtest-descriptives-2.svg [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-9] (42)
 * A JASP-Tests/R/tests/figs/BinomialTestBayesian/binomialtestbayesian-prior-posterior-1.svg [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-10] (94)
 * A JASP-Tests/R/tests/figs/BinomialTestBayesian/binomialtestbayesian-prior-posterior-2.svg [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-11] (94)
 * A JASP-Tests/R/tests/figs/BinomialTestBayesian/binomialtestbayesian-sequential-analysis-1.svg [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-12] (100)
 * A JASP-Tests/R/tests/figs/BinomialTestBayesian/binomialtestbayesian-sequential-analysis-2.svg [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-13] (100)
 * A JASP-Tests/R/tests/figs/ContingencyTablesBayesian/contingencytablesbayesian-log-odds-ratio.svg [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-14] (77)
 * A JASP-Tests/R/tests/figs/Correlation/correlation-correlation-matrix.svg [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-15] (280)
 * A JASP-Tests/R/tests/figs/CorrelationBayesian/correlationbayesian-correlation.svg [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-16] (319)
 * A JASP-Tests/R/tests/figs/CorrelationBayesianPairs/correlationbayesianpairs-prior-posterior.svg [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-17] (98)
 * A JASP-Tests/R/tests/figs/CorrelationBayesianPairs/correlationbayesianpairs-robustness-check.svg [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-18] (77)
 * A JASP-Tests/R/tests/figs/CorrelationBayesianPairs/correlationbayesianpairs-scatterplot.svg [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-19] (168)
 * A JASP-Tests/R/tests/figs/CorrelationBayesianPairs/correlationbayesianpairs-sequential-analysis.svg [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-20] (94)
 * A JASP-Tests/R/tests/figs/Descriptives/descriptives-boxplot.svg [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-21] (175)
 * A JASP-Tests/R/tests/figs/Descriptives/descriptives-correlation.svg [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-22] (271)
 * A JASP-Tests/R/tests/figs/Descriptives/descriptives-distribution.svg [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-23] (53)
 * A JASP-Tests/R/tests/figs/ExploratoryFactorAnalysis/exploratoryfactoranalysis-path-diagram.svg [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-24] (64)
 * A JASP-Tests/R/tests/figs/PrincipalComponentAnalysis/principalcomponentanalysis-path-diagram.svg [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-25] (30)
 * A JASP-Tests/R/tests/figs/RegressionLinear/regressionlinear-residuals-covariates.svg [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-26] (162)
 * A JASP-Tests/R/tests/figs/RegressionLinear/regressionlinear-residuals-dependent.svg [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-27] (160)
 * A JASP-Tests/R/tests/figs/RegressionLinear/regressionlinear-residuals-histogram.svg [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-28] (58)
 * A JASP-Tests/R/tests/figs/RegressionLinear/regressionlinear-residuals-predicted.svg [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-29] (160)
 * A JASP-Tests/R/tests/figs/RegressionLinear/regressionlinear-residuals-q-q.svg [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-30] (166)
 * A JASP-Tests/R/tests/figs/TTestBayesianIndependentSamples/ttestbayesianindependentsamples-descriptives.svg [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-31] (49)
 * A JASP-Tests/R/tests/figs/TTestBayesianIndependentSamples/ttestbayesianindependentsamples-prior-posterior.svg [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-32] (92)
 * A JASP-Tests/R/tests/figs/TTestBayesianIndependentSamples/ttestbayesianindependentsamples-robustness-check.svg [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-33] (79)
 * A JASP-Tests/R/tests/figs/TTestBayesianIndependentSamples/ttestbayesianindependentsamples-sequential-analysis.svg [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-34] (100)
 * A JASP-Tests/R/tests/figs/TTestBayesianOneSample/ttestbayesianonesample-descriptives.svg [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-35] (40)
 * A JASP-Tests/R/tests/figs/TTestBayesianOneSample/ttestbayesianonesample-prior-posterior.svg [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-36] (90)
 * A JASP-Tests/R/tests/figs/TTestBayesianOneSample/ttestbayesianonesample-robustness-check.svg [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-37] (84)
 * A JASP-Tests/R/tests/figs/TTestBayesianOneSample/ttestbayesianonesample-sequential-analysis.svg [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-38] (100)
 * A JASP-Tests/R/tests/figs/TTestBayesianPairedSamples/ttestbayesianpairedsamples-descriptives.svg [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-39] (47)
 * A JASP-Tests/R/tests/figs/TTestBayesianPairedSamples/ttestbayesianpairedsamples-prior-posterior.svg [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-40] (94)
 * A JASP-Tests/R/tests/figs/TTestBayesianPairedSamples/ttestbayesianpairedsamples-robustness-check.svg [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-41] (78)
 * A JASP-Tests/R/tests/figs/TTestBayesianPairedSamples/ttestbayesianpairedsamples-sequential-analysis.svg [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-42] (99)
 * A JASP-Tests/R/tests/figs/TTestIndependentSamples/ttestindependentsamples-descriptives.svg [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-43] (49)
 * A JASP-Tests/R/tests/figs/TTestOneSample/ttestonesample-descriptives.svg [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-44] (40)
 * A JASP-Tests/R/tests/figs/TTestPairedSamples/ttestpairedsamples-descriptives.svg [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-45] (47)
 * A JASP-Tests/R/tests/figs/deps.txt [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-46] (6)
 * A JASP-Tests/R/tests/testthat.R [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-47] (7)
 * A JASP-Tests/R/tests/testthat/helper-misc.R [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-48] (11)
 * A JASP-Tests/R/tests/testthat/helper-plots.R [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-49] (3)
 * A JASP-Tests/R/tests/testthat/helper-tables.R [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-50] (4)
 * A JASP-Tests/R/tests/testthat/test-ancova.R [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-51] (236)
 * A JASP-Tests/R/tests/testthat/test-ancovabayesian.R [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-52] (157)
 * A JASP-Tests/R/tests/testthat/test-anova.R [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-53] (270)
 * A JASP-Tests/R/tests/testthat/test-anovabayesian.R [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-54] (151)
 * A JASP-Tests/R/tests/testthat/test-anovarepeatedmeasuresbayesian.R [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-55] (183)
 * A JASP-Tests/R/tests/testthat/test-binomialtest.R [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-56] (31)
 * A JASP-Tests/R/tests/testthat/test-binomialtestbayesian.R [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-57] (44)
 * A JASP-Tests/R/tests/testthat/test-contingencytables.R [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-58] (174)
 * A JASP-Tests/R/tests/testthat/test-contingencytablesbayesian.R [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-59] (111)
 * A JASP-Tests/R/tests/testthat/test-correlation.R [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-60] (66)
 * A JASP-Tests/R/tests/testthat/test-correlationbayesian.R [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-61] (61)
 * A JASP-Tests/R/tests/testthat/test-correlationbayesianpairs.R [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-62] (76)
 * A JASP-Tests/R/tests/testthat/test-descriptives.R [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-63] (90)
 * A JASP-Tests/R/tests/testthat/test-exploratoryfactoranalysis.R [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-64] (57)
 * A JASP-Tests/R/tests/testthat/test-principalcomponentanalysis.R [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-65] (59)
 * A JASP-Tests/R/tests/testthat/test-regressionlinear.R [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-66] (314)
 * A JASP-Tests/R/tests/testthat/test-regressionloglinear.R [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-67] (61)
 * A JASP-Tests/R/tests/testthat/test-regressionloglinearbayesian.R [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-68] (96)
 * A JASP-Tests/R/tests/testthat/test-reliabilityanalysis.R [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-69] (47)
 * A JASP-Tests/R/tests/testthat/test-ttestbayesianindependentsamples.R [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-70] (106)
 * A JASP-Tests/R/tests/testthat/test-ttestbayesianonesample.R [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-71] (89)
 * A JASP-Tests/R/tests/testthat/test-ttestbayesianpairedsamples.R [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-72] (93)
 * A JASP-Tests/R/tests/testthat/test-ttestindependentsamples.R [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-73] (103)
 * A JASP-Tests/R/tests/testthat/test-ttestonesample.R [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-74] (70)
 * A JASP-Tests/R/tests/testthat/test-ttestpairedsamples.R [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-75] (76)
 * D JASP-Tests/analysesTests/test_summarystatsttestbayesianindepenedentsamples.R [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-76] (102)
 * D JASP-Tests/analysesTests/test_summarystatsttestbayesianonesample.R [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-77] (98)
 * D JASP-Tests/analysesTests/test_summarystatsttestbayesianpairedsamples.R [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-78] (98)
 * D JASP-Tests/run_tests.R [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-79] (34)
 * D JASP-Tests/utils_test.R [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-80] (200)
 * M Resources/Library/ReliabilityAnalysis.json [https://github.com/jasp-stats/jasp-desktop/pull/2115/files#diff-81] (144)

PATCH LINKS:
 * https://github.com/jasp-stats/jasp-desktop/pull/2115.patch [https://github.com/jasp-stats/jasp-desktop/pull/2115.patch]
 * https://github.com/jasp-stats/jasp-desktop/pull/2115.diff [https://github.com/jasp-stats/jasp-desktop/pull/2115.diff]

**Comment by TimKDJ** [comment]
Apologies, wrong Erik-Jan!


________________________________

**Comment by Erik-Jan** [comment]
Okay, "del" it is!


E.J. Duyvené de Wit 06-50668589 Arnhem On Thu, Nov 02, 2017 at 2:48pm, Tim de Jong < notifications@github.com [notifications@github.com] > wrote:
Apologies, wrong Erik-Jan!


________________________________

**Comment by Erik-Jan** [comment]
This is the third time that I receive one of your emails even though I have nothing to do with you.


Please remove my adress from your list.


Sincerely,


E.J. Duyvené de Wit 06-50668589 Arnhem On Thu, Nov 16, 2017 at 9:31am, bruno boutin < notifications@github.com [notifications@github.com] > wrote:
Merged #2115 [https://github.com/jasp-stats/jasp-desktop/pull/2115] .

**Pull request merged**
