### PR TITLE
jaspColumn improvements

### PR DESCRIPTION
**Pull request by JorisGoosen**
set analysisId to -1 in database on creation
make errormessage from jaspHtml show
use checkForFix branch of jaspBase

part of the fix for https://github.com/jasp-stats/INTERNAL-jasp/issues/2427 (AddColumnField and Distributions together can mess up the data)

### CODE REVIEW

**Comment by JorisGoosen** [comment]
I think I might have accidentally dropped a commit from this?

**Comment by JorisGoosen** [comment]
found it

**Comment by JorisGoosen** [comment]
image

For computed columns from analyses only.
Columns from analyses that arent computed (from Distributions) get a dropdown that allows you to cut it free now.

**Comment by JorisGoosen** [comment]
Ok, so I couldnt let go apparently, but Ive now also added some support for https://github.com/jasp-stats/INTERNAL-jasp/issues/694
Not quite computed columns, but you can now add columns from R as shown in: https://github.com/jasp-stats/jaspTestModule/blob/2ca3c9f5428d3a33356fa1b711ec7323e0f577a3/R/testAnalysisColumns.R#L23-L42

This should make it possible for https://github.com/jasp-stats/jasp-issues/issues/101 and other things to be implemented finally

**Comment by JorisGoosen** [comment]
we should probably test undo/redo well with this

**Comment by shun2wang** [comment]
If pacehoders in "long name" and "description" field will never showing😜

the field width seems (from qml code) has a good fix for multiple languages.

**Comment by JorisGoosen** [comment]
also fixed labelwidth for @shun2wang ;)
image

> If pacehoders in "long name" and "description" field will never showing😜 

?

**Comment by shun2wang** [comment]
I mean:
`placeholderText:	qsTr("<Fill in a more descriptive name of the column>")`

for long name field will never show because it always repalced by default value? but also the `description` of '...' will not showing.

but it doesn't matter...Or we can use tooltip here.

**Comment by JorisGoosen** [comment]
Aah yeah, well, thats ok :p

Im happy if it works, but some tooltips might be good.
right now im just gonna make sure it all aligns well and works

**Comment by JorisGoosen** [comment]
Ok I already found a bug... 
You can undo going from a analysisNotComputed column to a normal one. 
But that move resets the stored analysisID in the column so if you undo the "show analysis button" doesnt work anymore.
Its getting kind of late though so im gonna call it a night

**Comment by boutinb** [comment]
By testing it, I could find some issues:

- In a Distribution analysis, you can now overwrite an existing column. I thought this should be forbidden.
- If a computed column is added, a 'Show parent analysis' is displayed in the Variable window, but this button does not work.
- In Data Mode, if you click on a empty column (to create it), you get in the Variable window the 'Show parent analysis'
- In order to better see the missing values of a column, you have made the Variable Window higher. But if I make this height smaller (in another tab, eg. with the Label Editor tab), then if I switch to the Missing Values, I don't see the values anymore. To prevent this, we could increase the Variable Window minimum height.

**Comment by JorisGoosen** [comment]
> In a Distribution analysis, you can now overwrite an existing column. I thought this should be forbidden.

Only if the analysis itself made it!
Did you do `git submodule update` and start from a fresh buildfolder?

> If a computed column is added, a 'Show parent analysis' is displayed in the Variable window, but this button does not work.

"Added" ? By what? Manually or from an analysis?

> In Data Mode, if you click on a empty column (to create it), you get in the Variable window the 'Show parent analysis'

Oh ja? Ill check it out

> In order to better see the missing values of a column, you have made the Variable Window higher. But if I make this height smaller (in another tab, eg. with the Label Editor tab), then if I switch to the Missing Values, I don't see the values anymore. To prevent this, we could increase the Variable Window minimum height.

Or you just make it bigger again?

Ill just increase the minimum height for now or maybe split it

**Comment by JorisGoosen** [comment]
Ok I fixed all the mentioned problems

**Comment by boutinb** [comment]
Much better, but...
- Add column from a Destribution analysis, close the Analysis pane, so that you only see the data panel. Open the Variable Window, and click on the 'Show parent analysis' button: nothing happens
- Add a column from a Distribution analysis. Change the Computed type to 'Not computed'. Save and reload the JASP file: the column header has a Computed column icon, and the cells of this column are not editable
Screenshot 2023-11-08 at 14 34 22

**Comment by JorisGoosen** [comment]
> Add column from a Destribution analysis, close the Analysis pane, so that you only see the data panel. Open the Variable Window, and click on the 'Show parent analysis' button: nothing happens

This is not true, except for when you are in data-editing-mode.
Ill add a switch-to-analysis mode if you click that button

**Review by boutinb — APPROVED** [review]

**Pull request merged**
