### PR TITLE
The description for "Install Module" should come from QML

### PR DESCRIPTION
**Pull request by JorisGoosen**
- Fixes https://github.com/jasp-stats/INTERNAL-jasp/issues/1012

### CODE REVIEW

**Comment by boutinb** [comment]
If the Description.qml is missing, you get a confusing error message: 
Screen Shot 2020-09-14 at 14 08 59
A user-friendler error message would be welcome!

**Comment by JorisGoosen** [comment]
This issue is for "Install Module" not for "Install Developer Module" and so this error is entirely unrelated.

**Comment by JorisGoosen** [comment]
Well, one shouldn't be allowed to install it if the description is missing...

**Comment by boutinb** [comment]
> Well, one shouldn't be allowed to install it if the description is missing...

For sure, but with a message telling what is missing would be nicer.

**Comment by JorisGoosen** [comment]
Exactly, that is why i fixed it, the message isnt very clear but people should just put Description.qml in there, it's like nr 1 in to-do list of making a module :p

**Pull request merged**
