### PR TITLE
Bugs during 1. removing plot correlation matrix and 2. opening plots after reopenning jasp file

### PR DESCRIPTION
**Pull request by viktorsvetsky**
Today I experienced 2 bugs during using JASP.
1. In Regression/Correlation Matrix when I first tick in plots Correlation matrix, the plots has shown, but when I untick the box, program stopped working and displayed error message (screenshot attached).
screenshot

2. Each time I reopen jasp file all plots in results doesn't show and I have to reopen the results and untick and tick box by plots to see them again.
screenshot2

I'm using JASP 0.8.6.0 on Windows 10 Pro 64-bit.

### CODE REVIEW

**Comment by AlexanderLyNL** [comment]
Hi Viktor,

Thanks for reporting this, but could you please do so as an issue? 

https://github.com/jasp-stats/jasp-desktop/issues

As a pull request it'll go missing and mess up our build. Are you working on a custom build or on one of our releases?

Cheers, 
Alexander

**Comment by viktorsvetsky** [comment]
Hi.

Your instructions on github are confusing then. I ment to do it as issue but in your contributing guidelines is: „If you would like to create a new module/analysis, fix a bug you found, or implemented a feature, please submit a pull request“. So I did it as pull request.

Bit time wasting...

Viktor

**Comment by AlexanderLyNL** [comment]
Hi Viktor, 

Thanks for the feedback. The instructions on github are for when those people who implement a feature on their own branch and want to submit a fix they made already made on their own machine to then send it to our repository. The github system can indeed be a bit unclear. To report or request a feature, please consult the following blog post: 

https://jasp-stats.org/2018/03/29/request-feature-report-bug-jasp/

It's good that you point out this confusion with github and I'll phrase this more explicitly. 

Cheers,
Alexander

**Comment by viktorsvetsky** [comment]
Hi Alexander.

You’re welcome. I like what you do with JASP. I read that blogspot before I made the pull request. Again, there is separate paragraph about bugs where is no mention about issues or pull requests so I follow git hub instructions. Thank you for explaining. Next time I’ll know that issue is the right choice.

Viktor

**Pull request closed without merging**
