### PR TITLE
Enh: Disable ms-gaming overlay pop while JASP starting

### LINKED ISSUE #2479: [Bug]: ms-gaming overlay link
### JASP Version

0.18.1

### Commit ID

_No response_

### JASP Module

Unrelated

### What analysis are you seeing the problem on?

_No response_

### What OS are you seeing the problem on?

Windows 10

### Bug Description

The package informs me that a new gaming add on will be required whenever I try to upload a new data file. 

### Expected Behaviour

it should have neatly accepted the data file. 

### Steps to Reproduce

1. either the software patch may be provided 
2. OR this requirement may be dropped. 
3.
...

### Log (if any)

Screenshot 2023-12-19 110853

this may kindly be addressed 

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

### PR DESCRIPTION
**Pull request by shun2wang**
Fixes: https://github.com/jasp-stats/jasp-issues/issues/2479

This will change the rigistry of Windows system while install from msi installer, to disable annoying pop xbox gaming box message on some PC. this is a ready PR for merge.

### CODE REVIEW

**Review by boutinb — APPROVED** [review]

**Comment by JorisGoosen** [comment]
So I cannot test this sadly enough but the changes look good!

If anyone can confirm that the msis now no longer have this problem we can make sure this gets also gets integrated into the MSIX builds (because we will be moving towards that in the future).

Because it isnt in there it probably also means that this bug is now *only* solved for MSI and not for MSIX.

Maybe @RensDofferhoff and @shun2wang can talk later on how to get this registry setting into there?
Would be a shame to see this fix just disappear when we drop MSI

**Comment by shun2wang** [comment]
Yes, .msi has been tested and proven to work, however we have not received reports from msix users yet. 

And from the current solution, we can easily do it on msix. We only need to run a batch script for the Registration Entries (.reg) file while msix installing.

**Comment by JorisGoosen** [comment]
> And from the current solution, we can easily do it on msix. We only need to run a batch script for the Registration Entries (.reg) file while msix installing.

Ok sounds good!
Im assuming this problem will also occur for msix but who knows.
Just wanted to make sure someone noted the possible future regression here.

**Comment by JorisGoosen** [comment]
@FBartos says he tested the nightly from commit https://github.com/jasp-stats/jasp-desktop/commit/a271792aade72c283580a184cfd8e5d26c9eee94 and that he still gets the game thing

**Comment by shun2wang** [comment]
Ah, @FBartos did you install it from a .msi installer or zip file? it will only for .msi insaller. if is .msi which installation method was chosen( for current users/ for local machine)?

could you check these 3 paths of the registry entry and values, They are all values like 0x000000?
```

[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\GameDVR
"AppCaptureEnabled"

[HKEY_CURRENT_USER\System\GameConfigStore]
"GameDVR_Enabled"

[HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows\GameDVR]
"AllowGameDVR"
```

**Comment by FBartos** [comment]
I only used the .zip version. Not at my laptop right now but I can test the .msi on Monday

**Pull request merged**
