### PR TITLE
Minimal viable meta-analysis module

### PR DESCRIPTION
**Pull request by raoelg**
Added a meta-analysis module that is just complete enough to be usable. But needs a lot of work still. Many UX options not connected to any output behaviour yet. Variable names handling is wrong (quick hack to make it usable, but doesn’t work with non latin characters).

### CODE REVIEW

**Comment by boutinb** [comment]
@raoelg Can you set this module available only in DEBUG mode (with #ifdef QT_DEBUG in mainwindow.cpp and tabbar.cpp)?

**Comment by lindeloev** [comment]
Will this  be available in JASP and when? I had to use OpenMetaAnalyst for teaching this year but would really like to see it integrated in JASP so that students can use just one piece of software.

**Comment by AlexanderLyNL** [comment]
When do you need it? :)

**Comment by EJWagenmakers** [comment]
Hopefully in a week or two. No promises!
EJ

**Comment by lindeloev** [comment]
Awesome! I will add MA to the growing list of ways JASP is superior to SPSS.

Since you ask: I'll teach MA with exercises on Monday but I was just asking so that I could let students know when the could expect this to arrive in JASP. Task solved, thanks!

**Comment by AlexanderLyNL** [comment]
It's almost finished! Raoul and Tim are working very hard on it and only a couple of things need to be adjusted followed by some testing. Too bad we can't finish it before you discuss MA in your class, as that would have also provided a great additional test opportunity.

**Pull request closed without merging**
