### PR TITLE
[Reliability] changes list indexing requested in last PR

### PR DESCRIPTION
**Pull request by juliuspfadt**

### CODE REVIEW

**Review by Kucharssim — APPROVED** [review]

**Comment by Kucharssim** [comment]
Travis fails due to `The job exceeded the maximum time limit for jobs, and has been terminated.`, not because of failed tests per se. What is the problem here? Any ideas @JorisGoosen?

**Comment by JorisGoosen** [comment]
It seems it simply took too long... I don't see anything obvious that should be so slow, Ive restarted it to see what happens now.

**Comment by Kucharssim** [comment]
I lost track of this, sorry, can this be merged, or are we still waiting for something @juliuspf?

**Comment by juliuspfadt** [comment]
We are not waiting for anything, except new bugs maybe. But lately nothing new came in. So I don't see any reason not to merge.

**Comment by JorisGoosen** [comment]
@juliuspf did you also make a PR of this new code to Reliability? Would be great if you could do so otherwise.

**Pull request merged**
