### PR TITLE
Allow for selecting codepage for no-bom-workaround

### LINKED ISSUE #1842: [Bug]: Importing CSV with non-ascii created in local codepage in Excel has problems
### JASP Version

0.16.4 on Windows

### Bug Description

JASP 0.16.4 contains R 4.2.1 and this allows for using UTF-8 everywhere, this has fixed quite a few problems in JASP.
But there are still some issues with the workaround implemented in https://github.com/jasp-stats/jasp-desktop/commit/a0d1f6a9661e5c8180a9b9913673f0df785be566 (supporting reading CSV encoded in local codepage)
This is related also to https://github.com/jasp-stats/jasp-issues/issues/1811

These both (if working at all) would show garbled text, so instead of chinese (if the local codepage is that) you might get random unicode characters.

### Expected Behaviour
Expected behaviour would be to gracefully handle reading those files.

### Workaround
Luckily there is an easy workaround, exporting as a utf-8 csv. This also makes it possible to share your csv with other around the world and still allowing them to load it properly.

(As reading a csv in local codepage of chinese on a machine with local codepage dutch (for instance) would also fail.
This because Excel wouldnt know in which codepage the file was exported...

### PR DESCRIPTION
**Pull request by JorisGoosen**
Sadly enough it can't be used for spss/stata files.

Fixes https://github.com/jasp-stats/jasp-issues/issues/1842

If @shun2wang wants to build locally he can test this too, otherwise it can just be in a next nightly after boutin merges it.

### CODE REVIEW

**Comment by shun2wang** [comment]
yeah i'd love to. but i have some problems when I try to build by myself but on Windows with C compiler...

If someone can help me then I will have a try. with thanks.

**Comment by JorisGoosen** [comment]
Ah I can trigger a nightly, it just started and should be done in like 2 hours...

**Comment by shun2wang** [comment]
@boutinb Could you pls trigger a new build for this branch? with thanks.

**Comment by boutinb** [comment]
> @boutinb Could you pls trigger a new build for this branch? with thanks.

Yes it's building. Hopefully over 1 hour it is ready.

**Comment by boutinb** [comment]
It's in the Nightly: https://static.jasp-stats.org/Nightlies/

**Review by boutinb — APPROVED** [review]

**Review by shun2wang — APPROVED** [review]
I tested it, looks great!

**Pull request merged**
