### PR TITLE
JASP files with Audit Workflow analyses do not read well the TableView

### PR DESCRIPTION
**Pull request by boutinb**
Fixes https://github.com/jasp-stats/INTERNAL-jasp/issues/1290

### CODE REVIEW

**Review by koenderks — CHANGES_REQUESTED** [review]
Refreshing the loaded analysis does not apply the filter, see below (there are 0's):

image

**Comment by koenderks** [comment]
Other than that it looks good!

**Comment by boutinb** [comment]
It should work now

**Review by JorisGoosen — APPROVED** [review]

**Comment by JorisGoosen** [comment]
I approve the code and if the filter now works for @koenderks this can be merged.

**Review by koenderks — APPROVED** [review]
Yes, it looks like it is working!
image

**Pull request merged**
