### PR TITLE
Remove binding loop for scrollbars in componentsList

### PR DESCRIPTION
**Pull request by boutinb**
Fixes https://github.com/jasp-stats/jasp-test-release/issues/2662

### CODE REVIEW

**Comment by shun2wang** [comment]
Why mark this as draft? it looks good for me.

**Comment by boutinb** [comment]
> Why mark this as draft? it looks good for me.

Not yet, it does not look good when scrollbars appear. I have still to find the right way...

**Comment by shun2wang** [comment]
ah yes indeed...

**Comment by boutinb** [comment]
It seems to work now.

**Review by shun2wang — APPROVED** [review]

**Pull request merged**
