### PR TITLE
Data Library: Add Stroop data set that illustrates new Bayesian RM-ANOVA results

### PR DESCRIPTION
**Pull request by vandenman**
This data set and jasp file illustrate the discrepancy between the frequentist and Bayesian RM-ANOVA in JASP < 0.16.3. It also shows how the results for the new Bayesian RM-ANOVA are in line with the frequentist results.

### CODE REVIEW

**Review by Kucharssim — CHANGES_REQUESTED** [review]
Looks good, could you just change the description in the JASP file to follow the style of the other data library examples? Something like this:

**Description:**

This data set, "Stroop", provides reaction times of 19 participants in a 3 (Congruent, Incongruent, Neutral) x 2 (Stroop, Break) within subject design.

**Variables:** 

All columns contain reaction times (RTs) measured in miliseconds.

**Congruent-Stroop** - RTs in the Congruent-Stroop design cell.

**Incongruent-Stroop** - RTs in the Incongruent-Stroop design cell.

**Neutral-Stroop** - RTs in the Neutral-Stroop design cell.

**Congruent-Break** - RTs in the Congruent-Break design cell.

**Incongruent-Break** - RTs in the Inongruent-Break design cell.

**Neutral-Break** - RTs in the Neutral-Break design cell.

This example JASP file demonstrates a divergence between the Frequentist and Bayesian repeated measured ANOVA for JASP 0.16.3. Before JASP 0.16.3 the Bayesian repeated-measures ANOVA did not include random slopes for all but the highest order repeated-measures interaction, but the frequentist ANOVA does include these random slopes. 

In the results below, the frequentist ANOVA results shows that the effect of Congruency is significant (p < 0.05) while the effect of Preceding trial and the interaction between Preceding trial and Congruency are not significant (p > 0.05). The Bayesian ANOVA under the header: "legacy results without random slopes illustrates the behavior of JASP before 0.16.3. Surprisingly, there is Analysis of Effects table shows evidence in favor of Preciding trial (BFincl = 11.863), evidence against the interaction effect (BFexcl = 1/0.306 = 3.268), and undecisive evidence for the effect of Congruency (BFincl = 0.744). The Bayesian ANOVA under the header: "legacy results without random slopes illustrates the behavior of JASP from 0.16.3 onward. The models considered all include random slopes. Now the results are in agreement with the frequentist ANOVA. There is overwhelming evidence in favor of Congruency (BFincl = 5429) but undecisive evidence for the effect of Preceding trial and the interaction between Preceding trial and Congruency.

**References**

The data set was kindly provided by Ronen Hershman.

**Comment by vandenman** [comment]
Thanks! Here's the updated text:

image

**Comment by EJWagenmakers** [comment]
Looks good. Two suggestions:
1. Twice, you open apostrophes with <"legacy results...>, but there are no matching closing apostrophes.
2. According to Duncan Luce, the term "response times" is preferred over "reaction times" (unless people are pressing a button to a flash of light, say)
EJ

**Comment by vandenman** [comment]
@EJWagenmakers good catch! Below the new text, changes are highlighted.
image

**Review by Kucharssim — APPROVED** [review]

**Pull request merged**
