### PR TITLE
Changing language let the VariablesList small

### PR DESCRIPTION
**Pull request by boutinb**
Fixes jasp-stats/INTERNAL-jasp#819

### CODE REVIEW

**Comment by boutinb** [comment]
I know this fix is awkward... It might be worth a hotfix release

**Comment by JorisGoosen** [comment]
Could this be towards `stable` instead of development?

**Comment by JorisGoosen** [comment]
Also, maybe it would be worthwhile to check the warning in the output of Qt. I noticed a new warning about bindings or values so check out this:
https://doc.qt.io/qt-5/qml-qtqml-binding.html#restoreMode-prop
The warning I see on language change is `Warning: The default value is Binding.RestoreBinding. This will change in Qt 6.0 to Binding.RestoreBindingOrValue.` So maybe setting that in the original definition of the Binding helps?
Would be a bit less ugly and dependent on the current version behaving weirdly

**Comment by boutinb** [comment]
The warning comes from the ScrollBar (and the restoreMode should be set indeed), but it does not seem to be related to this problem.

**Comment by JorisGoosen** [comment]
No, but I thought if you replace the binding on `Layout.preferredHeight` (the original one) with a full `Binding{}` maybe it works better?

But If this solution works...

**Comment by boutinb** [comment]
You pushed it already.... Your hint (with the Binding) did not work.

**Comment by JorisGoosen** [comment]
Yes I know I pushed it already, I figured that your fix was as good as any and that you would notice the email that I pushed it as easily as a comment stating the fact that I was going to push it and then pushing it ;)

**Pull request merged**
