### PR TITLE
Remove 'force(col)' from LDA plotting functions

### PR DESCRIPTION
**Pull request by koenderks**
Changes in unit tests are due to letting the limits of the axes depend on the breaks created in JASPgraphs.

### CODE REVIEW

**Comment by koenderks** [comment]
@TimKDJ Apparently the unit test fails again...but on my jasptools the plots are fine now. Maybe you can take a quick look when you find the time?

**Comment by TimKDJ** [comment]
The size of the y-axis "Density" is what's different. Is this controlled by JASPgraphs or ggplot?

**Comment by koenderks** [comment]
By ggplot, but after rebasing more plots bail (also bayesian correlation matrix etc...)

**Comment by TimKDJ** [comment]
Yeah that's my bad, I merged Lexi's rewrite of the Correlation and Don's change of JASPgraphs today, but Don's thing negates Lexi's changes to the plot

**Comment by TimKDJ** [comment]
If you rebase now, then you should be able to remake just the lda classification plots

**Comment by koenderks** [comment]
Worked, this can be merged.

**Pull request merged**
