### PR TITLE
fix linux build action broken

### PR DESCRIPTION
**Pull request by shun2wang**

### CODE REVIEW

**Comment by RensDofferhoff** [comment]
Goodmorning.
I'd rather update the Qt version of the github action. I have done so now lets see if that works

**Comment by shun2wang** [comment]
Okay, thanks.

**Comment by shun2wang** [comment]
but maybe it's better to add the ninja tools back because it was failed action so I removed it.
and you can just push it.

**Comment by RensDofferhoff** [comment]
did that and it seems to work now! Thanks!

**Pull request closed without merging**
