### PR TITLE
Data library updates (GLMMS: Larks & Owls)

### PR DESCRIPTION
**Pull request by FBartos**
So, I have a few JASP analyses that could be added to the JASP library.

First, I'm adding this one to the mixed models, if the PR looks good, I would add the remaining ones.
(I changed the numbering as Mixed Models should not be last.)

fixes: https://github.com/jasp-stats/INTERNAL-jasp/issues/1877

### CODE REVIEW

**Review by Kucharssim — CHANGES_REQUESTED** [review]
Looks good to me. Just two little comments for the .jasp file

1. Can you make the title inside of the results panel "Larks and Owls: Classical Generalized Linear Models"?
2. Can you provide description for all variables in the data set, not only the variables that you use in the analysis?

Do you want to add more files into this PR, or are you planning to make additional PRs?

**Comment by FBartos** [comment]
Thanks, I will add the suggestions.

What do you prefer? Adding the other library files here or in a new PR?

**Comment by Kucharssim** [comment]
Here is fine :)

**Comment by FBartos** [comment]
I changed the title, added a description to some of the variables, and I removed other variables that I did not want to spend time figuring out and describing :)

**Review by Kucharssim — APPROVED** [review]

**Pull request merged**
