### PR TITLE
install JASP

### PR DESCRIPTION
**Pull request by pythonbaby2019**
I can't install JASP on the Windows Home Edition, it shows that I need Qt plugin,how to do， THANK U

### CODE REVIEW

**Comment by AlexanderLyNL** [comment]
Dear pythonbaby2019, 

It might be easiest if you download JASP via

https://jasp-stats.org/download/

Cheers,
Alexander

**Comment by pythonbaby2019** [comment]
Thank you

But what is mean of Closed #3526<https://github.com/jasp-stats/jasp-desktop/pull/3526>.

I have the JASP,But I can not install it successful


发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: AlexanderLyNL<mailto:notifications@github.com>
发送时间: 2019年9月10日 22:33
收件人: jasp-stats/jasp-desktop<mailto:jasp-desktop@noreply.github.com>
抄送: pythonbaby2019<mailto:decai.xu2019@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [jasp-stats/jasp-desktop] install JASP (#3526)


―

**Comment by AlexanderLyNL** [comment]
You're trying to change the software with this pull request. As it wouldn't be good to incorporate your changes to the software, I closed it. 

What you should do is go to the website

https://jasp-stats.org/download/

and download an installer there, which help you install JASP.

**Comment by pythonbaby2019** [comment]
OK thank you
I try it


发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: AlexanderLyNL <notifications@github.com>
发送时间: Tuesday, September 10, 2019 10:43:02 PM
收件人: jasp-stats/jasp-desktop <jasp-desktop@noreply.github.com>
抄送: pythonbaby2019 <decai.xu2019@outlook.com>; Author <author@noreply.github.com>
主题: Re: [jasp-stats/jasp-desktop] install JASP (#3526)


You're trying to change the software with this pull request. As it wouldn't be good to incorporate your changes to the software, I closed it.

What you should do is go to the website

https://jasp-stats.org/download/

and download an installer there, which help you install JASP.

―

**Comment by pythonbaby2019** [comment]
[cid:image002.png@01D5682A.3D4A1CC0]
After I finished  installation of JASP, Open it，it wil show above information，
Can you help me solve above issue？
Thank you


________________________________
发件人: AlexanderLyNL <notifications@github.com>
发送时间: Tuesday, September 10, 2019 10:43:02 PM
收件人: jasp-stats/jasp-desktop <jasp-desktop@noreply.github.com>
抄送: pythonbaby2019 <decai.xu2019@outlook.com>; Author <author@noreply.github.com>
主题: Re: [jasp-stats/jasp-desktop] install JASP (#3526)


You're trying to change the software with this pull request. As it wouldn't be good to incorporate your changes to the software, I closed it.

What you should do is go to the website

https://jasp-stats.org/download/

and download an installer there, which help you install JASP.

―

**Comment by AlexanderLyNL** [comment]
I'm sorry, but I can't see any image.

**Comment by pythonbaby2019** [comment]
[cid:image003.png@01D5682B.165AF5C0]
Can you see above image？
When I open it ，it will show above，thank you


________________________________
发件人: AlexanderLyNL <notifications@github.com>
发送时间: Tuesday, September 10, 2019 10:53:08 PM
收件人: jasp-stats/jasp-desktop <jasp-desktop@noreply.github.com>
抄送: pythonbaby2019 <decai.xu2019@outlook.com>; Author <author@noreply.github.com>
主题: Re: [jasp-stats/jasp-desktop] install JASP (#3526)


I'm sorry, but I can't see any image.

―

**Comment by AlexanderLyNL** [comment]
You can email the image to a.ly@jasp-stats.org, perhaps that's easier.

**Pull request closed without merging**
