### PR TITLE
Add option to disable ALTNavMode in settings + fix mac special char issue

### LINKED ISSUE #2160: [Bug]: PL Keyboard issues - using polish special characters on Mac (right command+a, e, o, l, n, c, s, etc.) difficult because conflicting shortcuts in JASP
### JASP Version

0.17.2

### Commit ID

_No response_

### JASP Module

Other Module

### What analysis are you seeing the problem on?

_No response_

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

When writing a note or imputing any text from keyboard if I try to use polish character such as "ó" - that you create by pressing right command + o, I run into the issue where JASP displays its shortcut map. So there is a conflict with inner JASP keybaord shortcuts and system shortcuts. I tried to change those shortcuts in JASP, but can't see how to do it. Is it possible to disable it? 

You can see a short video representing this issue: https://link.instytutpsychologiibiznesu.com/jasp1 

### Expected Behaviour

"ó" should be outputted while right command + o is pressed. 

### Steps to Reproduce

1. switch language to polish (polish programmer layout)
2. press right command and o to make "ó" sign 

### Log (if any)

_No response_

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

### PR DESCRIPTION
**Pull request by RensDofferhoff**
Fixes: https://github.com/jasp-stats/jasp-issues/issues/2160

There is now an accessibility option in UI options: 

image

### CODE REVIEW

**Review by JorisGoosen — APPROVED** [review]
looks good to me and works, @boutinb ?

**Review by JorisGoosen — APPROVED** [review]

**Comment by iGrzegorz** [comment]
I am happy that it is solved so fast, where can I get the dmg file including this fix to test it?

**Comment by JorisGoosen** [comment]
Are you on ARM/apple-silicon?

**Comment by iGrzegorz** [comment]
Yes

W dniu czw., 15.06.2023 o 12:09 Joris Goosen ***@***.***>
napisał(a):

**Comment by JorisGoosen** [comment]
I can see about building some nightlies later today, they appear at https://static.jasp-stats.org/Nightlies/

**Comment by iGrzegorz** [comment]
thanks!

**Comment by JorisGoosen** [comment]
Or maybe next week...

**Comment by JorisGoosen** [comment]
@iGrzegorz you can try this: https://static.jasp-stats.org/Nightlies/macOS-arm64/JASP-nightly-multibridgeMacArmworkaround-9dc5de1e2d64d8e784c4cbf7be7705b43656efa7.dmg

**Comment by iGrzegorz** [comment]
@JorisGoosen unfortunately MacOs doesn't allow me to run it. 

It says: ""JASP" file cannot be opened; Apple cannot check for malware. This software needs to be updated. For more information, contact the developer." 

Zrzut ekranu 2023-06-19 o 16 59 53

**Comment by RensDofferhoff** [comment]
@iGrzegorz  Go to apps in finder and open it there using: right click -> open.
We dont sign nightlies.

**Comment by iGrzegorz** [comment]
Thanks, the issue with entering Polish special characters is gone! Kudos! 🙌

**Comment by RensDofferhoff** [comment]
Great!
Thank you for the bug report :)

**Pull request merged**
