### PR TITLE
Use R Source with a JSON format

### PR DESCRIPTION
**Pull request by boutinb**
This follows PR https://github.com/jasp-stats/jasp-desktop/pull/4488

Examples have been added in jaspTestModule in testQmlSource analysis: https://github.com/jasp-stats/jaspTestModule/blob/main/inst/qml/testQmlSource.qml

### CODE REVIEW

**Comment by boutinb** [comment]
@JorisGoosen & @FBartos Could you review this PR?

**Comment by FBartos** [comment]
I thought I would check it up once it's in a nightly again, so I don't have to struggle with building JASP

**Comment by JorisGoosen** [comment]
Well, if @boutinb can push the branch to `jasp-stats/jasp-desktop` I can easily make a nightly for you.

**Comment by JorisGoosen** [comment]
I actually meant just pushing `jaspQmlSource` to upstream...
Not merging it in as I haven't had the time to review this...

**Comment by JorisGoosen** [comment]
Well the code looks quite reasonable!

What would be nice is if @boutinb adds documentation for this qml-element. Because how would people know how to use it?

**Comment by boutinb** [comment]
Yes I will do it: https://github.com/jasp-stats/INTERNAL-jasp/issues/1303

**Pull request merged**
