### PR TITLE
EmptyValues updates should work (also for files from 0.18.1)

### PR DESCRIPTION
**Pull request by JorisGoosen**
Make sure changes are updated in database
Also prepare the upgradeDB function in databaseInterface for future changes

I stopped working on the refactor of EmptyValues, thatll be for post-0.18.2
This should at least make empty values per column etc work for files from 0.18.1 (and perhaps more)

### CODE REVIEW

**Comment by boutinb** [comment]
Could you provide a reproduction path of what this PR solves? 
There is indeed an archive version issue you solved. And you just removed a not used column 'emptyValuesJson' in the table column. But I don't see any problem you solved in the empty values handling.

**Comment by JorisGoosen** [comment]
> Could you provide a reproduction path of what this PR solves? There is indeed an archive version issue you solved. And you just removed a not used column 'emptyValuesJson' in the table column. But I don't see any problem you solved in the empty values handling.

- open 0.18.1, open file from data library, save it somewhere
- build `development`
- load aforementioned file
- add missing values to a column (for instance '1' to contBinom)
- save file
- close file and load just saved file
- look at empty values in contBinom or whatever
- be amazed at the lack of them

For a bonus, I think it crashes if you try to then set empty values on the column but I might've misremembered.

**Comment by JorisGoosen** [comment]
It also makes sure the database is upgraded at the right moment

**Comment by boutinb** [comment]
There was still a problem: the workspace empty values are empty when a 0.18.1 JASP file is loaded. I have just added a commit to solve this.

**Comment by JorisGoosen** [comment]
So approved and it can be merged?

**Review by boutinb — APPROVED** [review]

**Pull request merged**
