### PR TITLE
Replace axes dropdown in PlotEditor by a tab view

### PR DESCRIPTION
**Pull request by boutinb**
As suggested in https://github.com/jasp-stats/INTERNAL-jasp/issues/1191

### CODE REVIEW

**Review by JorisGoosen — CHANGES_REQUESTED** [review]
Almost good, but I think the tabs at the top shouldn't have rounded corners, it looks a bit weird.
image

Actually the best would be to have at least the bottom non-rounded and the top I dont care. So either one of:
image
or
image

**Comment by boutinb** [comment]
I have added the border.

**Review by vandenman — APPROVED** [review]
I don't really understand the changes to the QML but it looks very nice in JASP!

image

**Comment by EJWagenmakers** [comment]
yes very nice

**Comment by TimKDJ** [comment]
Looks great already! My suggestion would be to make both tabs distinct. Something like:

tabs-plot-editor


That would also ensure the redo/undo buttons are not inside the y-axis/x-axis bar, which is good IMO as they are unrelated.

**Comment by JorisGoosen** [comment]
(Tims suggestion looks eerily similar to my first handdrawn suggestion ;) )

**Comment by boutinb** [comment]
Is it OK now?

**Comment by JorisGoosen** [comment]
image
Looks great!

**Review by JorisGoosen — APPROVED** [review]

**Pull request merged**
