### PR TITLE
Add jasp-stats/jaspBsts to jasp-desktop as a submodule

### PR DESCRIPTION
**Pull request by vandenman**
Supersedes https://github.com/jasp-stats/jasp-desktop/pull/4667

### CODE REVIEW

**Comment by Kucharssim** [comment]
Should not `jaspBSTS` be rather `jaspBsts`? Following our style guide, similarly as `jaspSem` and `jaspJags`

**Comment by vandenman** [comment]
I'll admit that the names in this PR are a bit messy, but I'm not 100% sure what you mean since there are multiple instances of BSTS:

- the name of the module is `jaspBsts`, and the name shown to users is `BSTS` (see [description.qml](https://github.com/jasp-stats/jaspBSTS/blob/3a29117491f60d36b45fe0921cb4b0f0741e78b6/inst/Description.qml#L6-L8
)).
- the URL of the GitHub repo is `jasp-stats/jaspBSTS` (I can change this if you want).
- the submodule path is `Modules/jaspBsts`, so that's the directory name.
- the title of this PR contains `jaspBSTS`, but that does not reflect the other naming schemes (although it is inconsistent).

which one would you like me to change?

**Comment by Kucharssim** [comment]
Yeah, sorry, I meant the repo url, just to be consistent

**Comment by vandenman** [comment]
Should be changed now!

**Review by JorisGoosen — APPROVED** [review]

**Pull request merged**
