### PR TITLE
Update result menu when changing language

### PR DESCRIPTION
**Pull request by boutinb**

### CODE REVIEW

**Comment by JorisGoosen** [comment]
Maybe next time you can add a reviewer to the PR?
But it seems I might have overlooked some things if I browse your PR.
Maybe you can fix the merge conflict?

**Comment by JorisGoosen** [comment]
And what is all the plural/multiple stuff for?

**Comment by boutinb** [comment]
'Add Note' is sometimes 'Add Notes', that's why I have added it...

**Comment by JorisGoosen** [comment]
Can we not just make it into "Add Note(s)"?
It seems like an awful lot of code just for that.

**Pull request merged**
