### PR TITLE
originalValueAsLabelIfEmpty

### PR DESCRIPTION
**Pull request by JorisGoosen**
Better in the model than in QML

Fixes https://github.com/jasp-stats/jasp-issues/issues/1655

### CODE REVIEW

**Review by shun2wang — COMMENTED** [review]
Suppose there are three corresponding value and label pairs: 1-A, 2-B, 3-C. If we remove the value of 3, but the legacy value and label are still leave in the variable window, it seems that `VariablesWindow.qml` is not getting the signal?

But this fix does make it clearer:-)

**Comment by JorisGoosen** [comment]
You mean the label of 3?
Ill try it though and see what you mean. But I cant repro

image
like this?

If I remove label C it just turns into 3

**Comment by shun2wang** [comment]
i mean remove all the 3 value from data cell.

**Comment by JorisGoosen** [comment]
> i mean remove all the 3 value from data cell.

And the problem would be what?
image
(I removed D from data nd after that the label D from 4)

**Comment by shun2wang** [comment]
图片

**Comment by JorisGoosen** [comment]
Ah you mean that 3/C is still in the vriables window?
That is not a problem is it?

**Comment by shun2wang** [comment]
yes, I do mean this.

**Comment by JorisGoosen** [comment]
Seems like proper behaviour to me, this way you would keep the original value if you add the label back again later during editing

**Comment by shun2wang** [comment]
yes, you are right at least it doesn't enter the analysis results and affect the data analysis.

**Review by shun2wang — APPROVED** [review]

**Pull request merged**
