### PR TITLE
Refresh some Data Library jasp files

### PR DESCRIPTION
**Pull request by Kucharssim**
Fixes https://github.com/jasp-stats/jasp-test-release/issues/1458
Fixes https://github.com/jasp-stats/jasp-test-release/issues/1497

### CODE REVIEW

**Comment by TimKDJ** [comment]
@boutinb always refreshes all the data library files in one go, so this might not be necessary (although it doesn't hurt to do this, of course)

**Comment by Kucharssim** [comment]
The prophet example needed a manual update, because the old file had outdated options which needed to be respecified manually in order to preserve the original results. The other files I did just because I saw it in the issues list.

**Comment by TimKDJ** [comment]
@Kucharssim could you have a look at the merge conflicts? Bruno [refreshed the data library](https://github.com/jasp-stats/jasp-desktop/pull/4624)

**Comment by Kucharssim** [comment]
I'll open a new PR for the Prophet example

**Pull request closed without merging**
