### PR TITLE
Remove unnecessary translation files

### PR DESCRIPTION
**Pull request by boutinb**
Fixes jasp-stats/INTERNAL-jasp#1375

### CODE REVIEW

**Comment by JorisGoosen** [comment]
Well, this all looks fine but did you also fix the github actions?

**Review by JorisGoosen — APPROVED** [review]

**Comment by boutinb** [comment]
> Well, this all looks fine but did you also fix the github actions?

Yes. Just tested

**Comment by JorisGoosen** [comment]
> > Well, this all looks fine but did you also fix the github actions?
> 
> Yes. Just tested

Aah so those aren't defined inside jasp-desktop then, okidoki.

**Comment by boutinb** [comment]
> > > Well, this all looks fine but did you also fix the github actions?
> > 
> > 
> > Yes. Just tested
> 
> Aah so those aren't defined inside jasp-desktop then, okidoki.

It is jasp-actions: https://github.com/jasp-stats/jasp-actions/blob/master/translations/generateLanguageFiles.sh

**Pull request merged**
