### PR TITLE
Catch exception on version parse failure

### PR DESCRIPTION
**Pull request by RensDofferhoff**
Should Mitigate: https://github.com/jasp-stats/jasp-issues/issues/1986

I could not reproduce the issue on any platform with all kinds of network shenanigans.
So I just catch the exception and leave it at that.

### CODE REVIEW

**Review by boutinb — APPROVED** [review]

**Comment by boutinb** [comment]
I think more exception handling is needed: the version is also read from JASP file, from Description.qml file... any malformed version string will crash JASP. Also any malformed description.qml file will crash JASP...
I have made another issue for this: https://github.com/jasp-stats/INTERNAL-jasp/issues/2235

**Comment by JorisGoosen** [comment]
But now nothing is done with a "refresh" reply like the user got in the issue no?

**Comment by RensDofferhoff** [comment]
> But now nothing is done with a "refresh" reply like the user got in the issue no?

That's true but I supposed it's a rather rare event and not worth adding handling for. But if you disagree I can take a look

**Comment by boutinb** [comment]
> > But now nothing is done with a "refresh" reply like the user got in the issue no?
> 
> That's true but I supposed it's a rather rare event and not worth adding handling for. But if you disagree I can take a look

Maybe we could catch the redirected signal: https://doc.qt.io/qt-5/qnetworkreply.html#redirected
These people may never hear about a new JASP version. That can be a pity.

**Comment by JorisGoosen** [comment]
> Maybe we could catch the redirected signal: [doc.qt.io/qt-5/qnetworkreply.html#redirected](https://doc.qt.io/qt-5/qnetworkreply.html#redirected)
These people may never hear about a new JASP version. That can be a pity.

Exactly! And this looks like an easy thing to add

**Comment by RensDofferhoff** [comment]
> > Maybe we could catch the redirected signal: [doc.qt.io/qt-5/qnetworkreply.html#redirected](https://doc.qt.io/qt-5/qnetworkreply.html#redirected)
> > These people may never hear about a new JASP version. That can be a pity.
> 
> Exactly! And this looks like an easy thing to add

Will do!

**Comment by boutinb** [comment]
I had a look further, and I see https://doc.qt.io/qt-6/qnetworkrequest.html#RedirectPolicy-enum, so a redirect http -> http should be automatic (NoLessSafeRedirectPolicy is the default). So we can still try to connect this redirect signal, but it does not seem to be the solution...

**Comment by RensDofferhoff** [comment]
> I had a look further, and I see https://doc.qt.io/qt-6/qnetworkrequest.html#RedirectPolicy-enum, so a redirect http -> http should be automatic (NoLessSafeRedirectPolicy is the default). So we can still try to connect this redirect signal, but it does not seem to be the solution...

Its probably because this is a html meta pragma that browsers use, not a proper redirect by http code 301/304. It's not part of http at all (status is 200)
See 
https://developer.mozilla.org/en-US/docs/Web/HTTP/Redirections
Do we still want to deal with it @JorisGoosen @boutinb?  I'm not sure this occurs all that much

**Comment by JorisGoosen** [comment]
Hmm, well if it isnt a proper redirect at all... Then lets drop it for now.

Although I do hope we don't end up with the situation where lots of people dont know about new versions :p

**Comment by JorisGoosen** [comment]
One problem I see with whats in this PR is that the logging at:
`Log::log() << "Unable to parse version number:\n " << e.what() << std::endl;` doesnt actually include the "version number" aka the html output. So even if we get a log from someone with this problem we couldnt even see whether there was such a weird response or not right?

As in the exception is a standard one no? So only the one number that fails is in it I guess

**Comment by shun2wang** [comment]
Ok, seems good and I cannot reproduce crash with nightly build. logs now like this:

```
......
00:00:02.431: Unable to parse version number:
 Module version not understood: <html>
<head>
<meta http-equiv='refresh' content='1; url=http://static.jasp-stats.org/JASP-Version.txt?cmd=redirect&arubalp=12345'>
</head>
</html>
00:00:03.323: MainWindow::resultsPageLoaded()
00:00:03.324: ResultsJsInterface::dequeueJsQueue has 1 waiting Js-scripts.
00:00:03.324: Running delayed script: 'window.setSelection(false);'.
00:00:06.369: EngineRepresentation::processEngineResumedReply() for engine #0
00:00:06.369: EngineRepresentation::sendSettings()
00:00:42.358: AsyncLoader::loadPackage(asyncloader)
00:00:42.359: SharedMemory::retrieveDataSet(17528)
00:00:42.457: Created shared mem with name JASP-DATA-17528
00:00:42.457: (Re)created dataset in shared mem with name JASP-DATA-17528
00:00:42.718: DataSetPackage::setDatabaseJson got:null
00:00:42.814: Loading analyses from jasp-file, entering loop.
00:00:42.814: Analyses::createFromJaspFileEntry
00:00:42.814: Checking if there are upgrade options for module 'jaspAnova' with function 'AnovaRepeatedMeasures' and version '0.17'!
00:00:42.814: Nope, no upgrades to be done.
......

```

**Pull request merged**
