### PR TITLE
Windows Installer takes too long to uninstall JASP

### PR DESCRIPTION
**Pull request by boutinb**
This is because removing the junctions takes really long.
For this try to remove these junctions with a script before uninstalling.

@JorisGoosen I have tried to modify the wix file so that it calls the JASP --remoce-junctions before uninstalling, but it still does not work. If you can have a look...

### CODE REVIEW

**Comment by JorisGoosen** [comment]
@boutinb the problem here was that you had forgotten to remove the "remove folder extension" that is making the MSI so slow. And your new code ran after that so it only slowed it down some more (but not much).

https://github.com/JorisGoosen/jasp-desktop/commit/03ca5b03be19266217f42a1a8979fda38425606c

Is how I fixed it so you could just cherry-pick it and test it (or not). I just did and it now doesnt take 20 minutes and the JASP folder is gone afterwards, so this should be good.

And if people cancel the uninstall and they lose their "Modules" folder they can just start `JASP.exe` in admin mode and it'll recreate them anyway.

**Comment by JorisGoosen** [comment]
Also, I think 
```
	<!-- Remember applicationfolderpath to later remove it entirely (mostly to get rid of Modules)-->
	<Property Id="APPLICATIONFOLDER">
		<RegistrySearch Key="SOFTWARE\JASP" Root="HKCU" Type="raw" Id="APPLICATIONFOLDER_REGSEARCH_USER" Name="Path" />
		<RegistrySearch Key="SOFTWARE\JASP" Root="HKLM" Type="raw" Id="APPLICATIONFOLDER_REGSEARCH_MACH" Name="Path" />
	</Property>
```

Can be removed as well as we do not need this anymore (cause we arent using that shitty extension)

**Review by JorisGoosen — APPROVED** [review]

**Comment by boutinb** [comment]
I haven't made your changes yet! Why did you merge this PR?

**Comment by JorisGoosen** [comment]
oow ja shit

**Comment by JorisGoosen** [comment]
I removed it and I will just squash and commit the changes I made at https://github.com/JorisGoosen/jasp-desktop/commit/03ca5b03be19266217f42a1a8979fda38425606c

**Comment by JorisGoosen** [comment]
https://github.com/jasp-stats/jasp-desktop/commit/187f78338c704de3e2024528c4e9abdc83204e6a

**Pull request merged**
