### PR TITLE
Data entry redux

### PR DESCRIPTION
**Pull request by JorisGoosen**
Speed up the filtered data entry model massively by not making gigantic jsons for everything.

This will add  "named filters" to jasp, which can be linked to jaspControls.
We could later extend on this functionality for analyses etc.

It also will make the filtered date entry model and r-side directly interface with the dataset and thus force the component to always be linked to a computed column.

### CODE REVIEW

**Comment by koenderks** [comment]
Don't forget the classical workflow (I see now that you adjusted only the Bayesian workflow?)

**Comment by JorisGoosen** [comment]
Its a draft and non-functional yet, I just opened it to have an easy way to see all the changes.

I still need to integrate the computed column into the dataentry thing all the way. Hopefully It'll be done next week

**Comment by JorisGoosen** [comment]
Only jaspAudit has some changes related to this PR

**Comment by JorisGoosen** [comment]
@koenderks @boutinb this is ready for review

for koen: I think it still works, maybe you can confirm :p
Should be much quicker for large datasets alround now.

**Comment by koenderks** [comment]
I'm currently trying this but I get:

image

I don't think this has to do with your changes, right? It is only in the dev module, not the non-dev audit. I can only test this once I can access the workflow, so I'll wait a bit.

**Comment by JorisGoosen** [comment]
You can build `development` right @koenderks ?
If you checkout this jasp-desktop branch (dataEntryRedux) and run git submodule update it ought to have the changes in jaspAudit as well. No need for development modules if you can build jasp.

This error of yours looks like you might need to clean up the buildfolder a bit?
(Unless you can build and run `development` with audit because then there is some other problem)

**Comment by koenderks** [comment]
Nice, it works fine. However, for a brief moment (long enough to make a screenshot however) you get this visual error:

image

Furthermore, I notice that the `selected` column is immediately made and visible but the `auditResult` column is not?

image

Works fast with dataset of 100000 rows!

**Comment by JorisGoosen** [comment]
> Nice, it works fine. However, for a brief moment (long enough to make a screenshot however) you get this visual error:

This is caused by the way Audit right now sets the filter-code and "auditResult" columnname only when you click "Fill Table". Only then is `auditResult created`. But `selected` isnt filled yet, so the filter returns nothing... So the error/warning.
Then on such an error I simply let it run again.
Now `selected` is filled and thus the next filter-return it shows stuff in the table.

This could be avoided by filling `selected` earlier.

Also, the initial values of the component are taking from `bookValue` but because they should only be set on the selected rows I have to wait until the filter returns to know which rows. So:
- Fill table, creates auditResults and sets filter to something like "selected > 0"
- Filter runs, but selected is empty so gets nothing. Mentions this to user.
- analysiscode runs, fills selected but gets no values from performAudit.
- filter runs again because of the earlier not-getting-anything
- now table knows which rows it should show. 
- first time it gets a usable filter it takes "initialValues" and sets it to the rows
- runs analysiscode again and now it gets all the info
 
> Furthermore, I notice that the `selected` column is immediately made and visible but the `auditResult` column is not?

Yes, the computed column is now created by the FilteredDataEntry thing. If you want it created earlier you should set `colName` earlier.

> Works fast with dataset of 100000 rows!

Right? :D

**Review by boutinb — APPROVED** [review]
Just added a commit to set the connections in the right object.

**Pull request merged**
