### PR TITLE
C RM ANOVA: implemented state system

### PR DESCRIPTION
**Pull request by raviselker**

### CODE REVIEW

**Comment by jonathon-love** [comment]
hey, there's a lot of spaces in here! and things are really getting messed up.
could you give these the once over?

**Comment by raviselker** [comment]
Spaces? The once over?

**Comment by jonathon-love** [comment]
spaces rather than tabs.

**Comment by raviselker** [comment]
Ah yeah, something went wrong in textwrangler. I'll get right on it.

**Comment by raviselker** [comment]
fixed it

**Comment by jonathon-love** [comment]
hey, does JASP still build for you? because after this merge, it doesn't for me.

**Comment by raviselker** [comment]
No, it says that there is a problem with ttestpairedsamples.R, but I didn't change that file so I don't really get what's happening.

**Comment by jonathon-love** [comment]
there's nothing wrong with ttestpairedsamples.R, that's just typical R error reporting.

you've missed a bracket or something in your code, but R doesn't realise that there's one missing until it gets to the very end of parsing all the R files; ttestpairedsamples just happens to be the last one.

**Pull request merged**
