### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Weblate](https://hosted.weblate.org/projects/jasp/jasp-desktop/) for JASP/JASP desktop.

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by FransMeerhoff** [comment]
Hi @JoKeyser 
Do you think I can merge this one, or do you still need more things for 0.14.1?
Cheers Frans

**Comment by JoKeyser** [comment]
@FransMeerhoff thanks for asking, I would say you can merge as-is, I personally won't have time to add much before 14.1 (do you know the day when its coming?).
However, maybe @tomtomme is working/planning on some more additions?

**Comment by tomtomme** [comment]
You can merge. I will translate again Friday to Sunday, but don't know what and how much. I have problems with the Bayesian stuff anyway.
@JoKeyser How would you translade prior and posterior? Vorherige und Spätere oder besser Ursprüngliche und Finale? Ich hab Bayes-Statistik bisher in keinem deutschen Lehrbuch gelesen...

**Comment by FransMeerhoff** [comment]
@JoKeyser @tomtomme Ok I wait with the merge, no hurry. Probably after our internal meeting next Tuesday we will have a planned release date.

**Comment by JoKeyser** [comment]
@tomtomme , regarding the translation of prior and posterior: It's obviously a central question, and I thought a lot about it already. My strong opinion is to use "(der) Prior" and "(der) Posterior" in most shorthand translations of JASPs interface. The most common translation in textbooks is "a-priori-Verteilung" and "a-posteriori-Verteilung", which is too cumbersome in my opinion to read, write, or speak about. Of course, the longer versions should be mentioned in explanatory/help texts that JASP provides.
A good resource to see this kind of translation in action is https://de.wikipedia.org/wiki/Bayessche_Statistik.
(I haven't written any of this, so this is an independent opinion.)

I have *never* seen a translation like "Vorherige", "Spätere", "Ursprüngliche", "Finale", and think these would be very impractical.

**Comment by tomtomme** [comment]
Thanks! That helps :)

**Comment by tomtomme** [comment]
> @tomtomme , regarding the translation of prior and posterior: It's obviously a central question, and I thought a lot about it already. My strong opinion is to use "(der) Prior" and "(der) Posterior" in most shorthand translations of JASPs interface. The most common translation in textbooks is "a-priori-Verteilung" and "a-posteriori-Verteilung", which is too cumbersome in my opinion to read, write, or speak about. Of course, the longer versions should be mentioned in explanatory/help texts that JASP provides.
> A good resource to see this kind of translation in action is https://de.wikipedia.org/wiki/Bayessche_Statistik.
> (I haven't written any of this, so this is an independent opinion.)
> 
> I have _never_ seen a translation like "Vorherige", "Spätere", "Ursprüngliche", "Finale", and think these would be very impractical.

I am just updating my earlier translations of Prior and Posterior. In most cases I feel that if those words are combined with "distribution" like "die Prior Verteilung" or "die Posterior Verteilung" it sounds wrong. I feel that the longer versions "die a priori Verteilung" or "die a posteriori Verteilung" sound better. Ist this just me because I am accustomed to a priori and post hoc from my use of G*Power? I also like "post hoc Verteilung" but from my research this use would be probably wrong and is also very rare on google scholar.
The longer terms are more common there. In longer explanatory texts I also tend to include (ursprüngliche) and (finale) as a hint for beginners. I hope this is acceptable and practical in the long run.

**Comment by JoKeyser** [comment]
@tomtomme to me, "Posterior" and "Prior" sound fine on their own. In cases where "-Verteilung" is added explicitly (e.g. to explain), I agree that "a-priori-Verteilung" and "a-posteriori-Verteilung" is a good compromise between us (but to me, "Prior-Verteilung" sounds also just fine).
I don't like "post-hoc-Verteilung", haven't seen it in texts yet.
Neither have I seen "ursprüngliche" or "finale", and I don't think they are particularly handy nor helpful, but of course that's just my (contrary) opinion.

My approach would be to stick to as few terms as possible, my impression from teaching is that multiple names for the same thing induce more confusion than to clear them up. Unless there is a good reason, I also like to remain close to English, so the terms don't get too "surprising" for people who know both, or are transitioning from one to the other.

**Comment by tomtomme** [comment]
@JoKeyser, thanks for your feedback. 

So moving forward as far as I understand we agree in the following points:

Prior & Posterior: 
Use untranslated when on their own

a priori & a posteriori: 
Use like an adjective when combined with a noun like distribution, if you like. Both are similar enough that this should not be able to create confusion.

post hoc:
Usually do not use in this context.

(ursprüngliche) & (finale):
Usually do not use. Only use as an additional translation along a priori & a posteriori in longer help texts if you feel, that they may be helpful for beginners. 


Off-topic:
For some years I tried to stick to one term for each. However after about 5 years I realized that I need to teach the german and the english term alongside. After another 5 years I realized that even that was not feasable in the long run. I frequently switched books and always recommend more than one for learning. Also reading papers with the students introduced even more variance in the used terms. I moved to a 2-sided synonym + translation sheet of most common terms, that my students have to cary around all day and probably are cursing me for it all day :D

**Comment by tomtomme** [comment]
In the meantime I imported my own glossary (some weeks ago) and updated it just now with the most common translations as found at GoogleScholar. If I knew synonyms for a term I searched both on scholar restricted to german sites for example like this: 

Statistik Korrelation "Streudiagramm" 
and
Statistik Korrelation "Scatterplot"

and then compared the number of results. The less common term then ended in brackets like:

Streudiagramm (seltener: Scatterplot)

**Comment by tomtomme** [comment]
Is there a reason, that the independent variable needs to be called covariate in the UI (true for JASP, SPSS, german, english)?
Why not just call it independent variable? I think that would be much more intuitive given that the dependent variable is called dependent variable in the same context / UI and not something else. 
I found that the independent variables might correlate with each other, so they co-vary and that that was the idea behind the word covariate. But that is not the intended use-case. The hope is almost always that they do not co-vary. They also might not correlate with the dependent variable, so in that case the dependent variable is not dependent at all but is still called that way. So even when the independent variables are not actually independent or even when they are just confounding variables (scheinkorrelierend with the dependent var) it would still be useful to call it independent variable - because thats the goal / the hope.
Or am I missing something here?

**Comment by tomtomme** [comment]
Also - is there a german translation for sparse regression?

**Comment by boutinb** [comment]
> Is there a reason, that the independent variable needs to be called covariate in the UI (true for JASP, SPSS, german, english)?
> Why not just call it independent variable? I think that would be much more intuitive given that the dependent variable is called dependent variable in the same context / UI and not something else.
> I found that the independent variables might correlate with each other, so they co-vary and that that was the idea behind the word covariate. But that is not the intended use-case. The hope is almost always that they do not co-vary. They also might not correlate with the dependent variable, so in that case the dependent variable is not dependent at all but is still called that way. So even when the independent variables are not actually independent or even when they are just confounding variables (scheinkorrelierend with the dependent var) it would still be useful to call it independent variable - because thats the goal / the hope.
> Or am I missing something here?

Maybe can @EJWagenmakers answers this question?

**Pull request merged**
