### PR TITLE
fix scaling in descriptives plots ANOVA

### PR DESCRIPTION
**Pull request by JohnnyDoorn**

### CODE REVIEW

**Comment by boutinb** [comment]
@JohnnyDoorn Some ANOVA unit tests are failing.

**Comment by vandenman** [comment]
@JohnnyDoorn please run `jasptools::manageTestPlots("anova")` to update the figures.

**Comment by boutinb** [comment]
@vandenman Is it safe to add this fix now to 0.12.2 now (even if the unit test fails)

**Comment by JohnnyDoorn** [comment]
yes I would think so!

**Comment by vandenman** [comment]
Ideally @JohnnyDoorn just fixes the failing tests. otherwise we lose oversight and every subsequent PR needs can't get merged before looking at the logs of Travis (every single PR will fail if you merge this).

**Comment by vandenman** [comment]
@boutinb this can be merged imo

**Pull request merged**
