### PR TITLE
bugfix: fix tooltip in the checkBox and RadioButton

### PR DESCRIPTION
**Pull request by shun2wang**
Fixes: https://github.com/jasp-stats/INTERNAL-jasp/issues/2525
Fixes: https://github.com/jasp-stats/INTERNAL-jasp/issues/2366

The reason is that sometimes the checkbox and radioButton cannot actually detect the mouse hover event.

### CODE REVIEW

**Comment by boutinb** [comment]
@shun2wang There was already a tooltip in jaspControl but it did not work. Handling attached property in c++ can be tricky: the attached property can be called directly if there is an import statement in the QML file without label. But by setting the tooltip directly in the MouseArea it works perfectly.

**Comment by boutinb** [comment]
I have added also a test in the jaspTestModule.

**Comment by shun2wang** [comment]
Great! so then we should remove all tooltip settings from other jaspControls component and just reuse it from C++ side?

I rebased this PR to head.

**Comment by shun2wang** [comment]
@boutinb This should get into 0.19.2 I gusess.

**Review by boutinb — APPROVED** [review]

**Pull request merged**
