### PR TITLE
Adds Reliability Module

### PR DESCRIPTION
**Pull request by JorisGoosen**
- From https://github.com/jasp-stats/Reliability/commit/23139fbcbde66c8d51a83f7aae4ec25612ab3d03

### CODE REVIEW

**Review by TimKDJ — CHANGES_REQUESTED** [review]
- [ ] Can you comment out the tests in the file `jasp-desktop/JASP-Tests/R/tests/testthat/test-reliabilityanalysis.R`? This analysis doesn't exist anymore so Travis complains

- [x] I couldn't get the analyses to actually work because `bayesrel` is missing. Any chance you (or @FransMeerhoff) could add it to required packages? 

@vandenman gave me these instructions when I tested the module:
1. Install the R package bayesrel from https://github.com/juliuspf/bayesrel (master branch).
2. Ensure that the version of Rcsdp is at least 0.1.57.

**Comment by FransMeerhoff** [comment]
@vandenman  'couldn't get the analyses to actually work because bayesrel is missing.' Should I add it ?

**Comment by vandenman** [comment]
@FransMeerhoff yes, please add `bayesrel` from https://github.com/juliuspf/bayesrel and Rcsdp from CRAN.

**Comment by FransMeerhoff** [comment]
@vandenman    OK for Mac Window follows

**Comment by TimKDJ** [comment]
So the package is added now (thanks @FransMeerhoff). If you remove the unit tests for the old analysis then this is fine. I found some errors in the analysis itself, but those are not for this PR

**Pull request merged**
