### PR TITLE
Add example JASP files for process module

### PR DESCRIPTION
**Pull request by maltelueken**
Adds three examples for the Process module.

Adds a new folder with index 20 in the data library for the Process module.

Moves the index of the Miscallaneous folder from 20 to 21.

### CODE REVIEW

**Review by FBartos — APPROVED** [review]
I only checked the .JASP files and they look all good. (the figures are really pretty btw)

**Comment by FBartos** [comment]
Not sure whether this is due to using a nightly, but switching from `Variables` to `Model number` in `Models` section crashes the analysis 
image

**Comment by maltelueken** [comment]
Not sure what happened with the force-push, but I made a PR to fix the issue when switching the model input type (https://github.com/jasp-stats/jaspProcess/pull/78). It seems like bootstrapping a model that was not fitted yet was the cause of the crash.

**Comment by shun2wang** [comment]
>Not sure what happened with the force-push

@maltelueken  Because @JorisGoosen  force-push changed the HEAD of the main branch, see this comment: https://github.com/jasp-stats/jasp-desktop/pull/5250#issuecomment-1875012985

for author of this PR you should do these in your fork by git:

```
git checkout add-process-examples
git fetch origin
git rebase origin/development
git push -f
```

**Comment by JorisGoosen** [comment]
Ooh sorry I fixed the stuff I did yesterday but that means it is back to normal ;)

**Comment by shun2wang** [comment]
Then this needs a rebase and force push again.

**Comment by maltelueken** [comment]
Done!

**Review by JorisGoosen — APPROVED** [review]
Looks good to me
If @FBartos can confirm the crash is gone we can merge this

**Comment by FBartos** [comment]
the crash is now solved

**Comment by maltelueken** [comment]
Thanks, will this already be included in the hotfix or in the next full release?

**Comment by JorisGoosen** [comment]
It will be in the hotfix

**Pull request merged**
