### PR TITLE
Selection Model - fixes

### PR DESCRIPTION
**Pull request by FBartos**
fixes: https://github.com/jasp-stats/jasp-test-release/issues/1032
fixes: https://github.com/jasp-stats/jasp-test-release/issues/1003
fixes: https://github.com/jasp-stats/jasp-test-release/issues/1031 (the same fix as for 1003)
fixes: https://github.com/jasp-stats/jasp-test-release/issues/1030
fixes: https://github.com/jasp-stats/jasp-test-release/issues/1000 (also updates help file for RoBMA)

### CODE REVIEW

**Comment by vandenman** [comment]
If I refresh the JASP file from https://github.com/jasp-stats/jasp-test-release/issues/1003 I get this error:

image

There's also a double BF01 in the RoBMA helpfile that I send you a screenshot of in slack.

the other issues seem fixed!

**Comment by FBartos** [comment]
interesting, I can't reproduce the error that's not fixed. Could you upload your .JASP file @vandenman please?

image

**Comment by vandenman** [comment]
here's the file: [modelSelectionTesting014(1).jasp.zip](https://github.com/jasp-stats/jasp-desktop/files/5345880/modelSelectionTesting014.1.jasp.zip) (rename and remove .zip).


I didn't change any options though.

**Comment by FBartos** [comment]
hmm, that's weird, I load it and click on refresh all and I get the correct behavior.
(I remmember seing a similar message while implementing the change, but all the updates are pushed there and I have nothing uncommited or unpushed)

image

**Comment by vandenman** [comment]
any particular package versions that I need?

**Comment by FBartos** [comment]
no, this shouldn't be related to any of that. it seems as if you didn't have all the commits

**Comment by FBartos** [comment]
maybe check that you have `weightr` package installed, but you wouldn't be run any other fixes without it...

**Comment by vandenman** [comment]
```r
> packageVersion("withr")
[1] ‘2.1.2’
```
is that version fine? 

~~Maybe @Kucharssim can also test if refreshing the JASP file a couple of comments up causes an error? Because if it's just me then this can be merged in my opinion.~~

**Comment by FBartos** [comment]
@vandenman that's a different package

**Comment by vandenman** [comment]
Oops, I failed to read! I indeed didn't have that package.

**Comment by vandenman** [comment]
I'm getting the same expected error message as in your screenshot now! So that solves the mystery.

**Review by vandenman — APPROVED** [review]

**Comment by FBartos** [comment]
awesome, glad that we figured it out

**Pull request merged**
