### PR TITLE
make signing identity overidable through easy env var

### PR DESCRIPTION
**Pull request by JorisGoosen**
this PR adds support for self-signed certificates for codesigning on macos.
iva also added a manual *with pictures* ;)

I think this works, but im still fighting with conan2 so cant really test it properly. But Im sure either or both of the fine gentlemen Ive added as reviewers will be able to help me out with that ;)

Id suggest creating a new fresh buildfolder next to your current one to avoid having to redownload all r-pkgs and all.
And maybe disabling most modules

### CODE REVIEW

**Review by boutinb — APPROVED** [review]
Nice!

**Comment by JorisGoosen** [comment]
@boutinb you built it entirely from scratch with the self-signed ID?

I would like someone else to try as well, @RensDofferhoff ?

Or is it good like this?
I tested it, Bruno tested it and maybe we can merge it and then let Mahdi or Gerko try it?

**Comment by RensDofferhoff** [comment]
Ill boot up my mac

**Review by RensDofferhoff — APPROVED** [review]
Great stuff! Lets merge it.
Build from fresh install folder, no issues

**Pull request merged**
