### PR TITLE
Core/restructure

### PR DESCRIPTION
**Pull request by akashrajkn**
Create New module - script - v0.1

- [x] Created .pri file to each module.
- [x] Moved common analyses to 'Common' folder
- [x] Delete unused analysis files
- [x] Create modules.json (contains all the modules and analyses)
- [x] Script to initialize new module
    - [x] Create ribbon files
    - [x] Create layout files
    - [x] Create resource and analyses files
    - [x] Create pri files
- [x] rename Reinforcement learning files
- ~~mainwindow.cpp - Remove hardcoded analyses tab numbers~~
- ~~Separate R files in different modules~~ - This will be done in a different pull request

### CODE REVIEW

**Comment by TimKDJ** [comment]
Give me a little heads up before this gets merged, because it will break JASPTools.

**Comment by akashrajkn** [comment]
@TimKDJ review for this pull request will be taken up after the upcoming release. Cheers.

**Comment by TimKDJ** [comment]
.R and .json files remain in place?

**Comment by akashrajkn** [comment]
That will be done in a separate pull request. (I still haven't figured out a good structure for custom R package for each module.)

**Pull request merged**
