### PR TITLE
API for upgrading jasp files

### PR DESCRIPTION
**Pull request by JorisGoosen**
For issue https://github.com/jasp-stats/INTERNAL-jasp/issues/590
Disable plotEditing in release

@koenderks after this is merged you can add upgrade options (the renaming you did) to `JASP-Desktop/modules/upgrader/upgrades.json`, but I can help with that.

### CODE REVIEW

**Comment by JorisGoosen** [comment]
@JohnnyDoorn did you remove/change any other options besides the homogeinity in ANOVA?
@TimKDJ are you aware of more changed options and analysis names that should be added to the central `upgrades.json`?

**Comment by TimKDJ** [comment]
Off the top of my head only the Bayesian correlation (which will be quite the test for your upgrade thingy), but that's not merged yet

**Comment by JorisGoosen** [comment]
I just realized I need to add, besides a manual of some kind, support for the new permanent errormsgs.

**Comment by JorisGoosen** [comment]
Well those messages aren't so important right now, can be done later.

**Pull request merged**
