### PR TITLE
Set right margin for the Binomial Testing Hypothesis

### PR DESCRIPTION
**Pull request by boutinb**
Fixes jasp-stats/jasp-test-release#990

### CODE REVIEW

**Review by FBartos — COMMENTED** [review]
it doesn't seem to fix the issue for me:
image

It seems to be connected to GUI scalling, zooming far enough will always hide the ride side.

**Comment by boutinb** [comment]
Are you sure you used my branch? The titles are already not at all at the place I set.

**Comment by FBartos** [comment]
I think so, I completely rebuild JASP using this PR.

This is how it looks on GUI 100% size:
image

and 50% size
image

**Comment by boutinb** [comment]
The filed width of the parameters were not scaled. I have just repaired that.

**Review by FBartos — APPROVED** [review]
It's working now, thanks! The same thing is gonna be necessary for the binomial estimation. Are you gonna add the changes there as well or should I create one more PR?

**Comment by boutinb** [comment]
> It's working now, thanks! The same thing is gonna be necessary for the binomial estimation. Are you gonna add the changes there as well or should I create one more PR?

I have changed the Binomial estimation as well. Plus 2 reference errors.

**Pull request merged**
