### PR TITLE
Double click for variableswindow/column

### PR DESCRIPTION
**Pull request by JorisGoosen**
As suggested in https://github.com/jasp-stats/jasp-test-release/issues/2343 and for https://github.com/jasp-stats/jasp-test-release/issues/2356

Also makes clicking around in the data waaaay less twitchy, also solves the clearing columns problem

### CODE REVIEW

**Comment by RensDofferhoff** [comment]
Delete still doesn't always work in selection.
When clicking on a cell while selecting instead of just hovering over it, the delete key is caught by the text edit element that is activated.
Is this desired behavior?

**Comment by RensDofferhoff** [comment]
Perhaps we shouldn't enter the text edit while shift is hold?
Otherwise we should probably cancel the selection on the click

**Comment by JorisGoosen** [comment]
Aah yeah I only looked at clicking the columnheaders for this issue, but I can have a look at the shift-clicking a cell.

> Perhaps we shouldn't enter the text edit while shift is hold?

Yeah that probably makes sense.

**Comment by JorisGoosen** [comment]
easy peasy

**Review by RensDofferhoff — APPROVED** [review]
Great!

**Pull request merged**
