### PR TITLE
Overtitles must be saved in state.

### PR DESCRIPTION
**Pull request by JorisGoosen**
Also added ignore to any columnnames starting with '.', like .isNewGroup

### CODE REVIEW

**Comment by JorisGoosen** [comment]
@koenderks can you check if the overtitles are now being saved?

**Comment by koenderks** [comment]
Not working for me.

**Comment by JorisGoosen** [comment]
Did you clean and rebuild JASP-R-Interface?

**Comment by koenderks** [comment]
Can't do that, I get error message: Cannot open include file: 'sys/time.h': No such file or directory

**Comment by JorisGoosen** [comment]
build it two more times ;)

**Comment by koenderks** [comment]
haha, got it working now. Overtitles are getting saved.

**Comment by JorisGoosen** [comment]
Nice!

**Pull request merged**
