### PR TITLE
Ship XQuartz libraries

### PR DESCRIPTION
**Pull request by boutinb**
Fixes https://github.com/jasp-stats/jasp-test-release/issues/2467

Load XQuartz package
Copy only the useful libraries
install_name_tool the libraries and the modules/R_X11.so and R_de.so files 
Sign them

### CODE REVIEW

**Comment by boutinb** [comment]
I have tested it on Mac ARM & Intel.

**Comment by JorisGoosen** [comment]
Ive turned on nightly builds so I can test it like that.

**Comment by boutinb** [comment]
> Ive turned on nightly builds so I can test it like that.

The modules need to be updated first (for jaspBase). I just did. I'm starting the nightly again.

**Comment by JorisGoosen** [comment]
Why did you not mention the changes to jaspBase here then?

**Comment by boutinb** [comment]
> Why did you not mention the changes to jaspBase here then?

Yes I should have done. I thought jaspBase was already updated in the shipXQuartz branch

**Review by JorisGoosen — APPROVED** [review]

**Comment by JorisGoosen** [comment]
Very nice!

**Pull request merged**
